In [1]:
import torch
import torch.nn as nn

In [ ]:
def loss_func(x, logits):
    '''
    x: [batch_size, seq_len]
    logits: [batch_size, seq_len, vocab_size]
    '''
    shift_labels = x[:,1:]

    shift_logits = logits[:,:-1,:]
    vocab_size = logits.size()[-1]
    
    shift_logits = shift_logits.contiguous().view(-1, vocab_size) # [batch_size * (seq_len-1), vocab_size]
    shift_labels = shift_labels.contiguous().view(-1) # [batch_size * (seq_len -1)]
    
    loss_fn = nn.CrossEntropyLoss(ignore_index=-100)
    loss = loss_fn(shift_logits, shift_labels)
    
    return loss

In [ ]:
batch_size, seq_len, vocab_size = 32, 20, 100000

x = torch.randint(0, vocab_size, size=(batch_size, seq_len))
logits = torch.rand(size=(batch_size, seq_len, vocab_size))
logits = torch.softmax(logits, dim=-1)

l = loss_func(x, logits)


In [9]:
l

tensor(11.5129)

In [ ]:
torch.randint(0, 1000, size=(2, 3))

tensor([[267, 143, 953],
        [271, 995, 761]])

In [7]:
torch.randint(0, 1000, size=(2, 3)).size()

torch.Size([2, 3])

In [22]:
x = torch.randint(0, 3, size=(1, 5))
x

tensor([[2, 0, 1, 1, 1]])

In [23]:
x[:, 1:]

tensor([[0, 1, 1, 1]])

In [25]:
logits = torch.rand(size=(1, 4, 3))
logits

tensor([[[0.5057, 0.0348, 0.6572],
         [0.1123, 0.5678, 0.9290],
         [0.2491, 0.2387, 0.3855],
         [0.2183, 0.3237, 0.4439]]])