In [1]:
import torch
import numpy as np

In [2]:
# torch.tensor() is a class constructor that creates a tensor from a list or a NumPy array.
# The tensor data type is inferred from the input data type.
list_data = [1, 2, 3, 4]
tensor_from_list = torch.tensor(list_data)
print(tensor_from_list) # tensor([1, 2, 3, 4])

tensor([1, 2, 3, 4])


In [3]:
# torch.tensor() can also create a tensor from a NumPy array.
np_array = np.array([1, 2, 3])
tensor_from_np_tensor = torch.tensor(np_array)
print(tensor_from_np_tensor) # tensor([1, 2, 3], dtype=torch.int32)

tensor([1, 2, 3])


In [5]:
torch.tensor([1, 2, 3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
a = torch.Tensor([[1, 2],[3, 4]])
print(a)
print(a.type)
np.array([[1, 2],[3, 4]])


tensor([[1., 2.],
        [3., 4.]])
<built-in method type of Tensor object at 0x1326c02f0>


array([[1, 2],
       [3, 4]])

In [7]:
b = torch.Tensor(2, 2)
print(b)


tensor([[0., 0.],
        [0., 0.]])


In [8]:
d = torch.tensor(((1, 2), (3, 4)))
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([[1., 2.],
        [3., 4.]])


In [11]:
d = torch.empty(2,3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# torch.zeros(shape) create tensors with all elements set to 0 
d = torch.zeros(2,3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# torch.ones(shape) create tensors with all elements set to 1
d = torch.ones(2,3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
d = torch.zeros_like(d)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
d = torch.ones_like(d)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
# torch.rand(shape)：create a tensor with elements randomly sampled from a uniform distribution over [0, 1).
d = torch.rand(2, 3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[0.4552, 0.7505, 0.5391],
        [0.1797, 0.0179, 0.0780]])


In [18]:
d = torch.linspace(10, 2, 3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([10.,  6.,  2.])


In [19]:
dd = torch.normal(mean=0, std=1, size=(2, 3), out=b)
print(b)
print(dd)

tensor([[-0.2736, -0.2299, -0.4318],
        [-0.8565, -2.3263,  0.9013]])
tensor([[-0.2736, -0.2299, -0.4318],
        [-0.8565, -2.3263,  0.9013]])


In [20]:
d = torch.Tensor(2, 2).uniform_(-1, 1)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[-0.1113,  0.3960],
        [ 0.2289, -0.3168]])


In [21]:
d = torch.randperm(10)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([0., 1., 8., 9., 3., 7., 5., 4., 6., 2.])


In [22]:
# torch.arange(start, end=None, step=1, dtype=None, layout=torch.strided, device=None, requires_grad=False)：create a 1-D tensor of size end-start/step.
d = torch.arange(2, 10, 2)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([2., 4., 6., 8.])
