In [1]:
import torch

In [2]:
dev = torch.device("mps")

In [3]:
def create_torch_tensors(device):
    x = torch.rand((10000, 10000), dtype=torch.float32)
    y = torch.rand((10000, 10000), dtype=torch.float32)
    x = x.to(device)
    y = y.to(device)

    return x, y

In [4]:
# dev = torch.device("cpu")
# dev = torch.device("cuda")

x, y = create_torch_tensors(dev)

In [5]:
a = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)
print(a)

tensor([2., 2.], device='mps:0')


In [7]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
print(i)
v = torch.tensor([1, 2, 3])
print(v)

tensor([[0, 1, 2],
        [0, 1, 2]])
tensor([1, 2, 3])


In [11]:
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

# index single element
element = tensor[0, 0]  # 1
print(element)

tensor(1)


In [13]:
# slice a row
slice_1 = tensor[0, :]  # [1, 2, 3]
print(slice_1)
slice_2 = tensor[:, 1]  # [2, 5]
print(slice_2)

tensor([1, 2, 3])
tensor([2, 5])


In [14]:
# change element
tensor[0, 0] = 7
print(tensor)  # [[7, 2, 3], [4, 5, 6]]

tensor([[7, 2, 3],
        [4, 5, 6]])


In [16]:
# shape attribute
shape = tensor.shape  # torch.Size([2, 3])
print(shape)
print(tensor)

torch.Size([2, 3])
tensor([[7, 2, 3],
        [4, 5, 6]])


In [18]:
# unsqueeze(dim) increase the dimension of the tensor by one
expanded_tensor = tensor.unsqueeze(0)  #  new shape = [1, 2, 3]
print(expanded_tensor.shape)
print(expanded_tensor)

torch.Size([1, 2, 3])
tensor([[[7, 2, 3],
         [4, 5, 6]]])


In [20]:
# reshape(shape) reshpe the tensor to the given shape
reshaped_tensor = tensor.reshape(6)  # new shape = [6]
print(reshaped_tensor.shape)
print(reshaped_tensor)

torch.Size([6])
tensor([7, 2, 3, 4, 5, 6])


In [22]:
# transpose(dim0, dim1) change two dimentions of the tensor
transposed_tensor = tensor.transpose(0, 1)  # new shape = [3, 2]
print(transposed_tensor)

tensor([[7, 4],
        [2, 5],
        [3, 6]])
