In [1]:
import torch

In [2]:
## add

a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.2463, 0.1423, 0.2080],
        [0.7482, 0.2024, 0.1716]])
tensor([[0.6269, 0.3867, 0.6763],
        [0.9443, 0.9877, 0.9227]])


In [4]:
print(a + b)
print(a.add(b))
print(torch.add(a, b))

tensor([[1.5001, 0.9157, 1.5606],
        [2.6369, 2.1779, 2.0169]])
tensor([[1.5001, 0.9157, 1.5606],
        [2.6369, 2.1779, 2.0169]])
tensor([[1.5001, 0.9157, 1.5606],
        [2.6369, 2.1779, 2.0169]])


In [5]:
print(a)
print(a.add_(b))
print(a)

tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])
tensor([[1.5001, 0.9157, 1.5606],
        [2.6369, 2.1779, 2.0169]])
tensor([[1.5001, 0.9157, 1.5606],
        [2.6369, 2.1779, 2.0169]])


In [6]:
## sub
print("==== sub res ====")
print(a - b)
print(torch.sub(a, b))

==== sub res ====
tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])
tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])


In [7]:
print(a.sub(b))
print(a.sub_(b))
print(a)

tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])
tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])
tensor([[0.8732, 0.5290, 0.8843],
        [1.6926, 1.1902, 1.0942]])


In [8]:
## mul
print("===== mul ====")
print(a * b) # element-wise multiplication
print(torch.mul(a, b))

===== mul ====
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])


In [10]:
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[0.3431, 0.0791, 0.4044],
        [1.5093, 1.1611, 0.9315]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.3431, 0.0791, 0.4044],
        [1.5093, 1.1611, 0.9315]])
tensor([[0.3431, 0.0791, 0.4044],
        [1.5093, 1.1611, 0.9315]])


In [ ]:
tensor = torch.tensor([1, 1, 1, 1])
matrix_product = tensor @ tensor.t()
print(matrix_product)

tensor(4)


In [15]:
# div
print("=== div ===")
print(a/b) # element-wise division
print(torch.div(a, b))
print(a.div(b))
print(a.div_(b))
print(a)

=== div ===
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])
tensor([[0.5474, 0.2046, 0.5980],
        [1.5983, 1.1755, 1.0096]])


In [16]:
### matmul

a = torch.ones(2, 1)
b = torch.ones(1, 2)
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a, b))
print(torch.mm(a, b))
print(a.mm(b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [18]:
## high deimensional tensor

a = torch.ones(1, 2, 3, 4)
print(a)
b = torch.ones(1, 2, 4, 3)
print(b)
print(a.matmul(b).shape)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
torch.Size([1, 2, 3, 3])
