In [ ]:
import torch

a = torch.rand(2, 2)
b = torch.rand(1, 2)

In [2]:
c = a + b
print(a)
print(b)
print(c)
print(c.shape)

tensor([[0.5625, 0.0675],
        [0.6651, 0.3461]])
tensor([[0.2110, 0.2527]])
tensor([[0.7734, 0.3202],
        [0.8761, 0.5989]])
torch.Size([2, 2])


In [3]:
a = torch.ones(2, 2)
b = torch.ones(1, 2)

In [4]:
c = a + b
print(a)
print(b)
print(c)
print(c.shape)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
torch.Size([2, 2])


In [6]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
broadcasted_addition = tensor + torch.tensor([1, 1, 1])
broadcasted_addition

tensor([[2, 3, 4],
        [5, 6, 7]])