In [1]:
import torch

a = torch.rand(2, 2)
a = a * 10
print(a)

tensor([[6.7647, 9.7478],
        [2.9630, 5.6677]])


In [2]:
print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))

tensor([[6., 9.],
        [2., 5.]])
tensor([[ 7., 10.],
        [ 3.,  6.]])
tensor([[ 7., 10.],
        [ 3.,  6.]])
tensor([[6., 9.],
        [2., 5.]])
tensor([[0.7647, 0.7478],
        [0.9630, 0.6677]])


In [ ]:
# x%2 = x − 2 × floor(x/2)
print(a % 2)

tensor([[0.7647, 1.7478],
        [0.9630, 1.6677]])


In [4]:
b = torch.tensor([[2, 3], [4, 5]],
                 dtype=torch.float)
print(torch.fmod(a, b))
print(torch.remainder(a, b))

tensor([[0.7647, 0.7478],
        [2.9630, 0.6677]])
tensor([[0.7647, 0.7478],
        [2.9630, 0.6677]])
