In [1]:
import torch
import numpy as np

a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.6334, 0.9809, 0.6044],
        [0.8953, 0.6391, 0.5780]])
tensor([[0.4672, 0.6495, 0.9165],
        [0.8428, 0.1350, 0.9366]])


In [2]:
print(torch.eq(a, b))
print(torch.equal(a, b))

tensor([[False, False, False],
        [False, False, False]])
False


In [3]:
print(torch.ge(a, b))
print(torch.gt(a, b))
print(torch.le(a, b))
print(torch.lt(a, b))
print(torch.ne(a, b))

tensor([[ True,  True, False],
        [ True,  True, False]])
tensor([[ True,  True, False],
        [ True,  True, False]])
tensor([[False, False,  True],
        [False, False,  True]])
tensor([[False, False,  True],
        [False, False,  True]])
tensor([[True, True, True],
        [True, True, True]])


In [5]:
# return a tensor with all elements set to False
# greater_than = tensor > tensor

a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)

torch.Size([2, 5])


In [6]:
print(torch.sort(a, dim=1, descending=False))

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))


In [7]:
val, ind = torch.sort(a, dim=1, descending=False)

In [8]:
print(val)

tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]])


In [9]:
print(ind)

tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]])


In [10]:
torch.sort(a, dim=-1, descending=False)

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))

In [11]:
torch.sort(a, dim=0, descending=False)

torch.return_types.sort(
values=tensor([[1, 3, 1, 3, 5],
        [2, 4, 4, 3, 5]]),
indices=tensor([[0, 1, 1, 0, 0],
        [1, 0, 0, 1, 1]]))

In [12]:
##topk
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])
print(a.shape)

print(torch.topk(a, k=2, dim=1, largest=False))

torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[1, 2],
        [1, 2]]),
indices=tensor([[3, 0],
        [3, 0]]))


In [14]:
print(torch.kthvalue(a, k=2, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))


In [15]:
print(torch.kthvalue(a, k=2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


In [18]:
print(torch.topk(a, k=3, dim=-1, largest=True))

torch.return_types.topk(
values=tensor([[5, 4, 3],
        [5, 4, 3]]),
indices=tensor([[4, 1, 2],
        [2, 4, 1]]))


In [19]:
a = torch.rand(2, 3)
print(a)
print(a/0)

tensor([[0.8380, 0.6963, 0.8849],
        [0.5962, 0.3153, 0.7761]])
tensor([[inf, inf, inf],
        [inf, inf, inf]])


In [20]:
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [21]:
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([False, False,  True])


In [22]:
a = torch.rand(2, 3)
print(a)
print(torch.topk(a, k=2, dim=1, largest=False))
print(torch.topk(a, k=2, dim=1, largest=True))

tensor([[0.1703, 0.5534, 0.6467],
        [0.3532, 0.7857, 0.0606]])
torch.return_types.topk(
values=tensor([[0.1703, 0.5534],
        [0.0606, 0.3532]]),
indices=tensor([[0, 1],
        [2, 0]]))
torch.return_types.topk(
values=tensor([[0.6467, 0.5534],
        [0.7857, 0.3532]]),
indices=tensor([[2, 1],
        [1, 0]]))
