In [2]:
import torch

a = torch.rand(2, 3)

print(a)
print(torch.mean(a, dim=0))
print(torch.sum(a, dim=0))
print(torch.prod(a, dim=0))

tensor([[0.8940, 0.1859, 0.4621],
        [0.3343, 0.6634, 0.9973]])
tensor([0.6142, 0.4246, 0.7297])
tensor([1.2283, 0.8493, 1.4593])
tensor([0.2989, 0.1233, 0.4608])


In [3]:
print(torch.mean(a, dim=-1))
print(torch.sum(a, dim=-1))
print(torch.prod(a, dim=-1))

tensor([0.5140, 0.6650])
tensor([1.5420, 1.9950])
tensor([0.0768, 0.2212])


In [4]:
print(torch.argmax(a, dim=0))
print(torch.argmin(a, dim=0))

tensor([0, 1, 1])
tensor([1, 0, 0])


In [5]:
print(torch.argmax(a, dim=-1))
print(torch.argmin(a, dim=-1))

tensor([0, 2])
tensor([1, 0])


In [6]:
print(torch.std(a))
print(torch.var(a))

tensor(0.3190)
tensor(0.1017)


In [7]:
print(torch.median(a))
print(torch.mode(a))

tensor(0.4621)
torch.return_types.mode(
values=tensor([0.1859, 0.3343]),
indices=tensor([1, 0]))


In [8]:
a = torch.rand(2, 2) * 10
print(a)
print(torch.histc(a, 6, 0, 0))

tensor([[7.3132, 8.0386],
        [3.2572, 6.2188]])
tensor([1., 0., 0., 1., 0., 2.])


In [12]:
a = torch.randint(0, 10, [2, 10])
print(a)

tensor([[0, 9, 2, 7, 7, 4, 2, 7, 6, 9],
        [1, 1, 6, 0, 1, 5, 2, 5, 9, 7]])
