In [5]:
import torch

torch.manual_seed(1)
mean = torch.rand(1, 2) * 100
print(mean)

tensor([[75.7632, 27.9311]])


In [6]:
std  = torch.rand(1, 2)
print(std)

tensor([[0.4031, 0.7347]])


In [7]:
print(torch.normal(mean, std))

tensor([[75.7880, 28.3876]])
