In [2]:
import torch
#torch.where

a = torch.rand(4, 4)
b = torch.rand(4, 4)


print(a)
print(b)

tensor([[0.8374, 0.4137, 0.2100, 0.8627],
        [0.7898, 0.5906, 0.2669, 0.3610],
        [0.6834, 0.2642, 0.6870, 0.6049],
        [0.0322, 0.6845, 0.1212, 0.7431]])
tensor([[0.7425, 0.6910, 0.4169, 0.7838],
        [0.0133, 0.7597, 0.6967, 0.7705],
        [0.7685, 0.2878, 0.8562, 0.9935],
        [0.4258, 0.6921, 0.9029, 0.8691]])


In [3]:
out = torch.where(a > 0.5, a, b)
print(out)

tensor([[0.8374, 0.6910, 0.4169, 0.8627],
        [0.7898, 0.5906, 0.6967, 0.7705],
        [0.6834, 0.2878, 0.6870, 0.6049],
        [0.4258, 0.6845, 0.9029, 0.7431]])


In [4]:
print("torch.index_select")
a = torch.rand(4, 4)
print(a)

torch.index_select
tensor([[0.8233, 0.8241, 0.4061, 0.0750],
        [0.1538, 0.6495, 0.7588, 0.6702],
        [0.5184, 0.8173, 0.2531, 0.1228],
        [0.3965, 0.1973, 0.5924, 0.3511]])


In [6]:
out = torch.index_select(a, dim=0, index=torch.tensor([0, 3, 2]))
print(out)

tensor([[0.8233, 0.8241, 0.4061, 0.0750],
        [0.3965, 0.1973, 0.5924, 0.3511],
        [0.5184, 0.8173, 0.2531, 0.1228]])


In [7]:
out = torch.index_select(a, dim=-1, index=torch.tensor([0, 3, 2]))
print(out)

tensor([[0.8233, 0.0750, 0.4061],
        [0.1538, 0.6702, 0.7588],
        [0.5184, 0.1228, 0.2531],
        [0.3965, 0.3511, 0.5924]])


In [20]:
a = torch.linspace(1, 16, 20)
print(a)

tensor([ 1.0000,  1.7895,  2.5789,  3.3684,  4.1579,  4.9474,  5.7368,  6.5263,
         7.3158,  8.1053,  8.8947,  9.6842, 10.4737, 11.2632, 12.0526, 12.8421,
        13.6316, 14.4211, 15.2105, 16.0000])


In [21]:
print("torch.gather")
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)

torch.gather
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


In [22]:
out = torch.gather(a, dim=0,
             index=torch.tensor([[0, 1, 1, 1],
                                 [0, 1, 2, 2],
                                 [0, 1, 3, 3]]))
print(out)
print(out.shape)

tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])
torch.Size([3, 4])


In [23]:
#dim=0, out[i, j, k] = input[index[i, j, k], j, k]
#dim=1, out[i, j, k] = input[i, index[i, j, k], k]
#dim=2, out[i, j, k] = input[i, j, index[i, j, k]]

In [ ]:
#torch.masked_index

print("torch.masked_index")
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)

torch.masked_index
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


In [25]:
mask = torch.gt(a, 8)
print(mask)

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [30]:
out = torch.masked_select(a, mask)
print(out)

tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [31]:
#torch.take

print("torch.take")
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)
b = torch.take(a, index=torch.tensor([0, 15, 13, 10]))
print(b)

torch.take
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 1., 16., 14., 11.])


In [32]:
#torch.nonzero
print("torch.take")
a = torch.tensor([[0, 1, 2, 0], [2, 3, 0, 1]])
out = torch.nonzero(a)
print(out)

torch.take
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])
