In [1]:
import torch

a = torch.zeros((2, 4))
b = torch.ones((2, 4))

In [ ]:
out = torch.cat((a,b), dim=0)
print(out)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
out = torch.cat((a,b),dim=1)
print(out)

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])


In [11]:
#torch.stack

print("torch.stack")
a = torch.linspace(1, 6, 6).view(2, 3)
print(a)
print(a.shape)

torch.stack
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [12]:
b = torch.linspace(7, 12, 6).view(2, 3)
print(b)
print(b.shape)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([2, 3])


In [13]:
out = torch.stack((a, b), dim=2)
print(out)
print(out.shape)

tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])


In [14]:
print(out[:, :, 0])
print(out[:, :, 1])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
out = torch.stack((a, b), dim=0)
print(out)
print(out.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [16]:
out = torch.stack((a, b), dim=1)
print(out)
print(out.shape)

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [17]:
out = torch.stack((a, b), dim=-1)
print(out)
print(out.shape)

tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])
