In [1]:
import torch

a = torch.rand((3, 4))
print(a)

tensor([[0.3879, 0.6310, 0.8973, 0.7343],
        [0.9448, 0.2703, 0.8635, 0.8906],
        [0.3231, 0.3374, 0.2473, 0.1156]])


In [3]:
out = torch.chunk(a, 2, dim=0)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.3879, 0.6310, 0.8973, 0.7343],
        [0.9448, 0.2703, 0.8635, 0.8906]]) torch.Size([2, 4])
tensor([[0.3231, 0.3374, 0.2473, 0.1156]]) torch.Size([1, 4])


In [4]:
out = torch.chunk(a, 2, dim=1)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.3879, 0.6310],
        [0.9448, 0.2703],
        [0.3231, 0.3374]]) torch.Size([3, 2])
tensor([[0.8973, 0.7343],
        [0.8635, 0.8906],
        [0.2473, 0.1156]]) torch.Size([3, 2])


In [7]:
out = torch.chunk(a, 2, dim=-1)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.3879, 0.6310],
        [0.9448, 0.2703],
        [0.3231, 0.3374]]) torch.Size([3, 2])
tensor([[0.8973, 0.7343],
        [0.8635, 0.8906],
        [0.2473, 0.1156]]) torch.Size([3, 2])


In [8]:
a = torch.rand((10, 4))
print(a)

tensor([[0.8584, 0.0062, 0.9579, 0.1329],
        [0.4705, 0.6059, 0.8280, 0.5540],
        [0.1132, 0.4364, 0.3333, 0.7152],
        [0.7005, 0.1181, 0.6376, 0.9952],
        [0.6418, 0.0500, 0.2071, 0.1989],
        [0.7963, 0.8434, 0.4416, 0.9524],
        [0.5166, 0.2038, 0.2128, 0.0584],
        [0.4653, 0.0209, 0.4144, 0.4898],
        [0.3882, 0.3466, 0.8245, 0.5316],
        [0.2175, 0.6084, 0.3361, 0.5832]])


In [9]:
out = torch.split(a, 3, dim=0)
print(len(out))

4


In [10]:
for t in out:
    print(t, t.shape)

tensor([[0.8584, 0.0062, 0.9579, 0.1329],
        [0.4705, 0.6059, 0.8280, 0.5540],
        [0.1132, 0.4364, 0.3333, 0.7152]]) torch.Size([3, 4])
tensor([[0.7005, 0.1181, 0.6376, 0.9952],
        [0.6418, 0.0500, 0.2071, 0.1989],
        [0.7963, 0.8434, 0.4416, 0.9524]]) torch.Size([3, 4])
tensor([[0.5166, 0.2038, 0.2128, 0.0584],
        [0.4653, 0.0209, 0.4144, 0.4898],
        [0.3882, 0.3466, 0.8245, 0.5316]]) torch.Size([3, 4])
tensor([[0.2175, 0.6084, 0.3361, 0.5832]]) torch.Size([1, 4])


In [11]:
out = torch.split(a, 3, dim=1)
print(len(out))

2


In [12]:
for t in out:
    print(t, t.shape)

tensor([[0.8584, 0.0062, 0.9579],
        [0.4705, 0.6059, 0.8280],
        [0.1132, 0.4364, 0.3333],
        [0.7005, 0.1181, 0.6376],
        [0.6418, 0.0500, 0.2071],
        [0.7963, 0.8434, 0.4416],
        [0.5166, 0.2038, 0.2128],
        [0.4653, 0.0209, 0.4144],
        [0.3882, 0.3466, 0.8245],
        [0.2175, 0.6084, 0.3361]]) torch.Size([10, 3])
tensor([[0.1329],
        [0.5540],
        [0.7152],
        [0.9952],
        [0.1989],
        [0.9524],
        [0.0584],
        [0.4898],
        [0.5316],
        [0.5832]]) torch.Size([10, 1])


In [13]:
out = torch.split(a, 3, dim=-1)

In [14]:
for t in out:
    print(t, t.shape)

tensor([[0.8584, 0.0062, 0.9579],
        [0.4705, 0.6059, 0.8280],
        [0.1132, 0.4364, 0.3333],
        [0.7005, 0.1181, 0.6376],
        [0.6418, 0.0500, 0.2071],
        [0.7963, 0.8434, 0.4416],
        [0.5166, 0.2038, 0.2128],
        [0.4653, 0.0209, 0.4144],
        [0.3882, 0.3466, 0.8245],
        [0.2175, 0.6084, 0.3361]]) torch.Size([10, 3])
tensor([[0.1329],
        [0.5540],
        [0.7152],
        [0.9952],
        [0.1989],
        [0.9524],
        [0.0584],
        [0.4898],
        [0.5316],
        [0.5832]]) torch.Size([10, 1])


In [15]:

out = torch.split(a, [1, 3, 6], dim=0)
for t in out:
    print(t, t.shape)

tensor([[0.8584, 0.0062, 0.9579, 0.1329]]) torch.Size([1, 4])
tensor([[0.4705, 0.6059, 0.8280, 0.5540],
        [0.1132, 0.4364, 0.3333, 0.7152],
        [0.7005, 0.1181, 0.6376, 0.9952]]) torch.Size([3, 4])
tensor([[0.6418, 0.0500, 0.2071, 0.1989],
        [0.7963, 0.8434, 0.4416, 0.9524],
        [0.5166, 0.2038, 0.2128, 0.0584],
        [0.4653, 0.0209, 0.4144, 0.4898],
        [0.3882, 0.3466, 0.8245, 0.5316],
        [0.2175, 0.6084, 0.3361, 0.5832]]) torch.Size([6, 4])
