In [1]:
import torch

a = torch.rand(2, 3)

print(a)

tensor([[0.3974, 0.8413, 0.3836],
        [0.8588, 0.9625, 0.8783]])


In [2]:
out = torch.reshape(a, (3, 2))

print(out)


tensor([[0.3974, 0.8413],
        [0.3836, 0.8588],
        [0.9625, 0.8783]])


In [3]:
print(torch.t(out))

tensor([[0.3974, 0.3836, 0.9625],
        [0.8413, 0.8588, 0.8783]])


In [4]:
print(torch.transpose(out, 0, 1))

tensor([[0.3974, 0.3836, 0.9625],
        [0.8413, 0.8588, 0.8783]])


In [6]:
a = torch.rand(1, 2, 3)
print(a)

tensor([[[0.5648, 0.3345, 0.5721],
         [0.2588, 0.0537, 0.5637]]])


In [7]:
out = torch.transpose(a, 0, 1)
print(out)
print(out.shape)

tensor([[[0.5648, 0.3345, 0.5721]],

        [[0.2588, 0.0537, 0.5637]]])
torch.Size([2, 1, 3])


In [8]:
out = torch.squeeze(a)
print(out)
print(out.shape)

tensor([[0.5648, 0.3345, 0.5721],
        [0.2588, 0.0537, 0.5637]])
torch.Size([2, 3])


In [9]:
out = torch.unsqueeze(a, -1)
print(out.shape)

torch.Size([1, 2, 3, 1])


In [14]:
out = torch.unbind(a, dim=0)
print(out)

(tensor([[0.5648, 0.3345, 0.5721],
        [0.2588, 0.0537, 0.5637]]),)


In [15]:
out = torch.unbind(a, dim=1)
print(out)

(tensor([[0.5648, 0.3345, 0.5721]]), tensor([[0.2588, 0.0537, 0.5637]]))


In [16]:
out = torch.unbind(a, dim=-1)
print(out)

(tensor([[0.5648, 0.2588]]), tensor([[0.3345, 0.0537]]), tensor([[0.5721, 0.5637]]))


In [21]:
print(a)
print(a.shape)

tensor([[[0.5648, 0.3345, 0.5721],
         [0.2588, 0.0537, 0.5637]]])
torch.Size([1, 2, 3])


In [19]:
print(torch.flip(a, dims=[2, 1]))

tensor([[[0.5637, 0.0537, 0.2588],
         [0.5721, 0.3345, 0.5648]]])


In [22]:
out = torch.rot90(a, -1, dims=[0, 2])
print(out)
print(out.shape)

tensor([[[0.5648],
         [0.2588]],

        [[0.3345],
         [0.0537]],

        [[0.5721],
         [0.5637]]])
torch.Size([3, 2, 1])


In [23]:
out = torch.rot90(a, -1)
print(out)
print(out.shape)

tensor([[[0.5648, 0.3345, 0.5721]],

        [[0.2588, 0.0537, 0.5637]]])
torch.Size([2, 1, 3])
