In [2]:
import torch
import numpy as np
import cv2

data = cv2.imread("test.png")

print(data)

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]]


In [3]:
cv2.imshow("test1", data)

In [4]:
# cv2.waitKey(0)

# a = np.zeros([2, 2])
out = torch.from_numpy(data)

In [5]:
out = out.to(torch.device("mps"))

print(out.is_cuda)


False


In [6]:
out = torch.flip(out, dims=[0])

out = out.to(torch.device("cpu"))

In [7]:
print(out.is_cuda)

False


In [ ]:
data = out.numpy()

cv2.imshow("test2", data)

cv2.waitKey(0)