In [1]:
import torch

In [2]:
class line(torch.autograd.Function):
    @staticmethod
    def forward(ctx, w, x, b):
        #y = w*x +b
        ctx.save_for_backward(w, x, b)
        return w * x + b

    @staticmethod
    def backward(ctx, grad_out):
        w, x, b = ctx.saved_tensors

        grad_w = grad_out * x
        grad_x = grad_out * w
        grad_b = grad_out

        return grad_w, grad_x, grad_b

In [3]:
w = torch.rand(2, 2, requires_grad=True)
x = torch.rand(2, 2, requires_grad=True)
b = torch.rand(2, 2, requires_grad=True)

In [4]:
out = line.apply(w, x, b)
out.backward(torch.ones(2, 2))

In [8]:
print(x)

tensor([[0.8505, 0.0734],
        [0.9959, 0.2702]], requires_grad=True)


In [9]:
print(w)

tensor([[0.9269, 0.1778],
        [0.5599, 0.2421]], requires_grad=True)


In [10]:
print(b)

tensor([[0.2919, 0.1664],
        [0.4984, 0.2801]], requires_grad=True)


In [11]:
print(x.grad)

tensor([[0.9269, 0.1778],
        [0.5599, 0.2421]])


In [12]:
print(w.grad)

tensor([[0.8505, 0.0734],
        [0.9959, 0.2702]])


In [13]:
print(b.grad)

tensor([[1., 1.],
        [1., 1.]])
