<a href="https://colab.research.google.com/github/lingduoduo/Deep-Learning/blob/master/PyTorch/01/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

/usr/local/lib/python3.9/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-11.8/nvvm/libdevice
find: ‘/proc/53/task/53/net’: Invalid argument
find: ‘/proc/53/net’: Invalid argument
/usr/local/cuda-11.8/nvvm/lib64/libnvvm.so
find: ‘/proc/53/task/53/net’: Invalid argument
find: ‘/proc/53/net’: Invalid argument


In [2]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import torch
print(torch.__version__)

1.13.1+cu116


In [5]:
print(torch.version.cuda)

11.6


In [ ]:
dev = torch.device("cpu")

In [ ]:
a = torch.tensor([2,2], device = dev)

In [ ]:
print(a)

tensor([2, 2])


In [ ]:
dev = torch.device("cuda")

In [ ]:
b = torch.tensor([2,2], device = dev)

In [ ]:
print(b)

tensor([2, 2], device='cuda:0')


In [ ]:
c = torch.tensor([2,2], dtype=torch.float32, device = dev)

In [ ]:
print(c)

tensor([2., 2.], device='cuda:0')


In [ ]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
e = torch.sparse_coo_tensor(i, v, (4, 4),
                            dtype=torch.float32,
                            device=dev)
print(e)

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1., 2., 3.]),
       device='cuda:0', size=(4, 4), nnz=3, layout=torch.sparse_coo)


In [ ]:
e.to_dense()

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

In [ ]:
dev = torch.device("cuda")
a = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)
b = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)

In [ ]:
print(a)

tensor([2., 2.], device='cuda:0')


In [ ]:
print(b)

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a + b)

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a.add(b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(torch.add(a, b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a.add_(b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a)

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a - b)

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a.sub(b))

tensor([2., 2.], device='cuda:0')


In [ ]:
print(torch.sub(a, b))

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a.sub_(b))

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a)

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a * b)

tensor([4., 4.], device='cuda:0')


In [ ]:
print(torch.mul(a, b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a.mul(b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a.mul_(b))

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a)

tensor([4., 4.], device='cuda:0')


In [ ]:
print(a / b)

tensor([2., 2.], device='cuda:0')


In [ ]:
print(torch.div(a, b))

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a.div(a))

tensor([1., 1.], device='cuda:0')


In [ ]:
print(a.div_(b))

tensor([2., 2.], device='cuda:0')


In [ ]:
print(a)

tensor([2., 2.], device='cuda:0')


In [ ]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [ ]:
print(a @ b)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(torch.matmul(a, b))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(torch.mm(a, b))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(a.mm(b))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.ones(1, 2, 3, 4)
b = torch.ones(1, 2, 4, 3)
print(a.matmul(b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [ ]:
print(a.matmul(b).shape)

torch.Size([1, 2, 3, 3])


In [ ]:
a = torch.tensor([1,2])

In [ ]:
print(torch.pow(a, 3))

tensor([1, 8])


In [ ]:
print(a**3)

tensor([1, 8])


In [ ]:
print(a.pow_(3))

tensor([1, 8])


In [ ]:
print(a)

tensor([1, 8])


In [ ]:
print(torch.exp(a))

tensor([2.7183e+00, 2.9810e+03])


In [ ]:
print(torch.exp_(a))

RuntimeError: ignored

In [ ]:
print(a.type())

torch.LongTensor


In [ ]:
a = torch.tensor([1,2], dtype=torch.float32)

In [ ]:
print(a.exp())

tensor([2.7183, 7.3891])


In [ ]:
print(a.exp_())

tensor([2.7183, 7.3891])


In [ ]:
print(torch.log(a))

tensor([1., 2.])


In [ ]:
print(a.log())

tensor([1., 2.])


In [ ]:
print(a.log_())

tensor([1., 2.])


In [ ]:
a

tensor([1., 2.])

In [ ]:
print(torch.sqrt(a))

tensor([1.0000, 1.4142])


In [ ]:
print(a.sqrt())

tensor([1.0000, 1.4142])


In [ ]:
print(a.sqrt_())

tensor([1.0000, 1.4142])


In [ ]:
a

tensor([1.0000, 1.4142])

In [6]:
import torch

In [7]:
import numpy as np

In [8]:
a = np.zeros([2, 2])

In [9]:
out = torch.from_numpy(a)

In [10]:
print(out)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
