<a href="https://colab.research.google.com/github/lingduoduo/Deep-Learning/blob/master/PyTorch/01/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

find: ‘/proc/57/task/57/net’: Invalid argument
find: ‘/proc/57/net’: Invalid argument
/usr/local/lib/python3.9/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-11.8/nvvm/libdevice
find: ‘/proc/57/task/57/net’: Invalid argument
find: ‘/proc/57/net’: Invalid argument
/usr/local/cuda-11.8/nvvm/lib64/libnvvm.so


In [2]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import torch
print(torch.__version__)

1.13.1+cu116


In [5]:
print(torch.version.cuda)

11.6


In [6]:
dev = torch.device("cpu")

In [7]:
a = torch.tensor([2,2], device = dev)

In [8]:
print(a)

tensor([2, 2])


In [9]:
dev = torch.device("cuda")

In [10]:
b = torch.tensor([2,2], device = dev)

In [11]:
print(b)

tensor([2, 2], device='cuda:0')


In [12]:
c = torch.tensor([2,2], dtype=torch.float32, device = dev)

In [13]:
print(c)

tensor([2., 2.], device='cuda:0')


In [14]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
e = torch.sparse_coo_tensor(i, v, (4, 4),
                            dtype=torch.float32,
                            device=dev)
print(e)

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1., 2., 3.]),
       device='cuda:0', size=(4, 4), nnz=3, layout=torch.sparse_coo)


In [15]:
e.to_dense()

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0')