In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('BAAI/bge-base-zh')

/Users/linghuang/miniconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
sentences_1 = [
    "At the global press conference for 'Singer 2025', Chen Chusheng repeatedly emphasized one point: 'Singing competitions must insist on being live!'",
    "Chen Chusheng spoke bluntly that back when he debuted (in 2007's 'Super Boy'), live broadcasting was an everyday thing. A singing show without a live broadcast has no soul."
]

sentences_2 = [
    "The margin financing balance refers to the difference between the amount of money used to buy stocks on margin and the amount repaid.",
    "The short selling balance refers to the difference between the daily amount of short-sold securities and the amount repaid."
]

embeddings_1 = model.encode(sentences_1)
embeddings_2 = model.encode(sentences_2)

In [3]:
embeddings_1

array([[-0.00606592,  0.02830052,  0.00888656, ..., -0.02672569,
        -0.00881802, -0.00689836],
       [-0.01139886,  0.03132079,  0.00601804, ..., -0.00919508,
        -0.00021329, -0.03312751]], dtype=float32)

In [4]:
similarity = embeddings_1@embeddings_2.T

In [5]:
similarity

array([[0.7425345, 0.7571777],
       [0.7173866, 0.7497162]], dtype=float32)

In [6]:
embeddings_1[0]@embeddings_1[1].T

np.float32(0.80679953)

In [7]:
queries = ["What is margin financing balance?", "What is short selling balance?"]
passages = [
    "The margin financing balance refers to the difference between the amount of money used to buy stocks on margin and the amount repaid.",
    "The short selling balance refers to the difference between the daily amount of short-sold securities and the amount repaid."
]

instructions = "Generate a representation for this sentence to retrieve relevant documents: "

q_embeddings = model.encode([instructions + q for q in queries], normalize_embeddings=True)
p_embeddings = model.encode(passages, normalize_embeddings=True)

In [8]:
sim = q_embeddings@p_embeddings.T
sim

array([[0.85175204, 0.7944076 ],
       [0.7879479 , 0.84088165]], dtype=float32)