<a href="https://colab.research.google.com/github/lingduoduo/Deep-Learning/blob/master/PyTorch/01/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

/usr/local/lib/python3.9/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-11.8/nvvm/libdevice
find: ‘/proc/53/task/53/net’: Invalid argument
find: ‘/proc/53/net’: Invalid argument
/usr/local/cuda-11.8/nvvm/lib64/libnvvm.so
find: ‘/proc/53/task/53/net’: Invalid argument
find: ‘/proc/53/net’: Invalid argument


In [2]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
import torch
print(torch.__version__)

/Users/linghuang/miniconda3/envs/torch/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.8.0


In [2]:
print(torch.version.cuda)

None


In [3]:
dev = torch.device("cpu")

In [4]:
a = torch.tensor([2,2], device = dev)

In [5]:
print(a)

tensor([2, 2])


In [8]:
# dev = torch.device("cuda")
dev = torch.device("mps")

In [9]:
b = torch.tensor([2,2], device = dev)

In [10]:
print(b)

tensor([2, 2], device='mps:0')


In [11]:
c = torch.tensor([2,2], dtype=torch.float32, device = dev)

In [12]:
print(c)

tensor([2., 2.], device='mps:0')


In [14]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
# e = torch.sparse_coo_tensor(i, v, (4, 4),
#                             dtype=torch.float32,
#                             device=dev)
e_cpu_sparse = torch.sparse_coo_tensor(i, v, (4, 4), dtype=torch.float32, device="cpu")

# use it on MPS by making it dense first
e = e_cpu_sparse.to_dense().to(dev)
print(e, e.device)
print(e)

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='mps:0') mps:0
tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='mps:0')


In [15]:
e.to_dense()

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='mps:0')

In [16]:
# dev = torch.device("cuda")
dev = torch.device("mps")
a = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)
b = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)

In [17]:
print(a)

tensor([2., 2.], device='mps:0')


In [18]:
print(b)

tensor([2., 2.], device='mps:0')


In [19]:
print(a + b)

tensor([4., 4.], device='mps:0')


In [20]:
print(a.add(b))

tensor([4., 4.], device='mps:0')


In [21]:
print(torch.add(a, b))

tensor([4., 4.], device='mps:0')


In [22]:
print(a.add_(b))

tensor([4., 4.], device='mps:0')


In [23]:
print(a)

tensor([4., 4.], device='mps:0')


In [24]:
print(a - b)

tensor([2., 2.], device='mps:0')


In [25]:
print(a.sub(b))

tensor([2., 2.], device='mps:0')


In [26]:
print(torch.sub(a, b))

tensor([2., 2.], device='mps:0')


In [27]:
print(a.sub_(b))

tensor([2., 2.], device='mps:0')


In [28]:
print(a)

tensor([2., 2.], device='mps:0')


In [29]:
print(a * b)

tensor([4., 4.], device='mps:0')


In [30]:
print(torch.mul(a, b))

tensor([4., 4.], device='mps:0')


In [31]:
print(a.mul(b))

tensor([4., 4.], device='mps:0')


In [32]:
print(a.mul_(b))

tensor([4., 4.], device='mps:0')


In [33]:
print(a)

tensor([4., 4.], device='mps:0')


In [34]:
print(a / b)

tensor([2., 2.], device='mps:0')


In [35]:
print(torch.div(a, b))

tensor([2., 2.], device='mps:0')


In [36]:
print(a.div(a))

tensor([1., 1.], device='mps:0')


In [37]:
print(a.div_(b))

tensor([2., 2.], device='mps:0')


In [38]:
print(a)

tensor([2., 2.], device='mps:0')


In [39]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [40]:
print(a @ b)

tensor([[1., 1.],
        [1., 1.]])


In [41]:
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])


In [42]:
print(torch.matmul(a, b))

tensor([[1., 1.],
        [1., 1.]])


In [43]:
print(torch.mm(a, b))

tensor([[1., 1.],
        [1., 1.]])


In [44]:
print(a.mm(b))

tensor([[1., 1.],
        [1., 1.]])


In [45]:
a = torch.ones(1, 2, 3, 4)
b = torch.ones(1, 2, 4, 3)
print(a.matmul(b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [46]:
print(a.matmul(b).shape)

torch.Size([1, 2, 3, 3])


In [47]:
a = torch.tensor([1,2])

In [48]:
print(torch.pow(a, 3))

tensor([1, 8])


In [49]:
print(a**3)

tensor([1, 8])


In [50]:
print(a.pow_(3))

tensor([1, 8])


In [51]:
print(a)

tensor([1, 8])


In [52]:
print(torch.exp(a))

tensor([2.7183e+00, 2.9810e+03])


In [54]:
b = torch.exp(a.float())
print(b)

tensor([2.7183e+00, 2.9810e+03])


In [55]:
print(a.type())

torch.LongTensor


In [56]:
a = torch.tensor([1,2], dtype=torch.float32)

In [57]:
print(a.exp())

tensor([2.7183, 7.3891])


In [58]:
print(a.exp_())

tensor([2.7183, 7.3891])


In [59]:
print(torch.log(a))

tensor([1.0000, 2.0000])


In [60]:
print(a.log())

tensor([1.0000, 2.0000])


In [61]:
print(a.log_())

tensor([1.0000, 2.0000])


In [62]:
a

tensor([1.0000, 2.0000])

In [63]:
print(torch.sqrt(a))

tensor([1.0000, 1.4142])


In [64]:
print(a.sqrt())

tensor([1.0000, 1.4142])


In [65]:
print(a.sqrt_())

tensor([1.0000, 1.4142])


In [66]:
a

tensor([1.0000, 1.4142])

In [69]:
import numpy as np

In [72]:
a = np.array([1, 2, 3], dtype=np.float32)

In [77]:
import sys, torch, numpy as np
print("Python:", sys.executable)
print("Torch:", torch.__version__, " at ", torch.__file__)
print("NumPy:", np.__version__, " at ", np.__file__)

Python: /Users/linghuang/miniconda3/envs/torch/bin/python
Torch: 2.8.0  at  /Users/linghuang/miniconda3/envs/torch/lib/python3.11/site-packages/torch/__init__.py
NumPy: 2.3.3  at  /Users/linghuang/miniconda3/envs/torch/lib/python3.11/site-packages/numpy/__init__.py


In [78]:
import numpy as np, torch
a = np.array([1, 2, 3], dtype=np.float32)
out = torch.tensor(a.tolist(), dtype=torch.float32)  # copies via Python list
print(out)

tensor([1., 2., 3.])


In [79]:
print(out)

tensor([1., 2., 3.])
