In [1]:
import torch
import numpy as np

### Tensor

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

- Scalar is a single number.
- Vector is an array of numbers.
- Matrix is a 2-D array of numbers.
- Tensors are N-D arrays of numbers.

In [3]:
np.array([0.0, 0.1, 0.3])
torch.tensor([0.0, 0.1, 0.2])

tensor([0.0000, 0.1000, 0.2000])

In [4]:
x = np.array([0.0, 0.1, 0.3])
torch.from_numpy(x)

tensor([0.0000, 0.1000, 0.3000], dtype=torch.float64)

In [6]:
np.ones(3)
torch.ones(3)

tensor([1., 1., 1.])

In [8]:
np.zeros(5)
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [10]:
np.ones(10)
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.eye(3)
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
np.arange(1,5,2)
torch.arange(1,5,2)

tensor([1, 3])

In [17]:
np.linspace(1,5,2)
torch.linspace(1,5,2)

tensor([1., 5.])

In [44]:
d = torch.zeros(2,3)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [45]:
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [22]:
np.random.rand(3,2)
torch.rand(2, 3)

tensor([[0.8632, 0.7223, 0.5323],
        [0.7446, 0.9398, 0.8634]])

In [48]:
d = torch.Tensor(2, 2).uniform_(-1, 1)
print(d)
print(d.type())

tensor([[ 0.4829,  0.4955],
        [-0.3262, -0.1285]])
torch.FloatTensor


In [27]:
# standard normal
np.random.randn(2, 4)
torch.randn(2,4)

tensor([[ 0.4851, -0.0987,  1.6798, -0.2318],
        [-0.2457,  0.3351,  0.5537, -0.1356]])

In [31]:
np.random.normal(0, 0.1, 10)
torch.normal(0, 0.1, size=(1, 10))

tensor([[ 0.0085, -0.0321,  0.0395,  0.1118,  0.0580, -0.0725,  0.0073, -0.0383,
         -0.0826,  0.1012]])

In [37]:
np.random.uniform(0, 1, 10)
torch.distributions.Uniform(low=0, high=1)

Uniform(low: 0.0, high: 1.0)

In [39]:
np.random.permutation(10)
torch.randperm(10)

tensor([9, 0, 1, 6, 4, 3, 5, 8, 2, 7])

In [54]:
torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

tensor([1., 2., 3.])

In [53]:
indices = torch.tensor([[0,1,1], [2,0,2]])
values = torch.tensor([2,3,4], dtype=torch.float32)
x = torch.sparse_coo_tensor(indices,values, [2, 4])
print(x)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([2., 3., 4.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)


In [2]:
a = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [3]:
b = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [4]:
c = a + b
print(c)

tensor([2., 4., 6.])


In [6]:
c = torch.sub(a, b)
print(c)

tensor([0., 0., 0.])


In [7]:
a.sub(b)
print(a)

tensor([1., 2., 3.])


In [8]:
a.sub_(b)
print(a)

tensor([0., 0., 0.])


In [10]:
d = b * c
print(d)

tensor([0., 0., 0.])


In [11]:
d = torch.mul(b, c)
print(d)

tensor([0., 0., 0.])


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
a.mul(b)

tensor([1, 4, 9])

In [13]:
a.mul_(b)

tensor([1, 4, 9])

In [14]:
print(a)

tensor([1, 4, 9])


In [16]:
c = a / b
print(c)

tensor([1., 2., 3.])


In [19]:
c = torch.div(a, b)
print(c)

tensor([1., 2., 3.])


In [20]:
a.div(b)

tensor([1., 2., 3.])

In [23]:
b

tensor([1, 2, 3])

In [27]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
b = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
a.div_(b)

tensor([1., 1., 1.])

Matrix computation

In [28]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [29]:
print(torch.mm(a, b))
print(torch.matmul(a, b))
print(a @ b)
print(a.mm(b))
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


对于高维的tensor， 矩阵乘法作用于最后两个维度

In [30]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(torch.matmul(a, b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [35]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
print(a)
print(torch.pow(a, 2))
print(a.pow(2))
print(a**2)
print(a.pow_(2))
print(a)

tensor([1., 2., 3.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])


In [36]:
print(torch.exp(a))
b = a.exp_()
print(b)

tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])


In [38]:
print(a)
print(torch.sqrt(a))
print(a.sqrt())
print(a.sqrt_())
print(a)

tensor([ 1.6487,  7.3891, 90.0171])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])


In [39]:
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))
print(torch.log_(a))
print(a)

tensor([0.3607, 1.4427, 3.2461])
tensor([0.1086, 0.4343, 0.9772])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])


In [2]:
a = torch.rand(2, 3)
b = torch.rand(3)

In [3]:
print(a)

tensor([[0.6836, 0.2217, 0.8508],
        [0.2915, 0.6192, 0.0198]])


In [11]:
print(a.shape)

torch.Size([2, 3])


In [4]:
print(b)

tensor([0.3733, 0.7068, 0.8890])


In [12]:
print(b.shape)

torch.Size([3])


In [5]:
c = a + b

In [6]:
print(c)

tensor([[1.0569, 0.9284, 1.7398],
        [0.6648, 1.3259, 0.9088]])


In [13]:
a = torch.rand(2, 1)
b = torch.rand(2)

In [15]:
print(a)

tensor([[0.6062],
        [0.4804]])


In [16]:
print(b)

tensor([0.0286, 0.4391])


In [14]:
a + b

tensor([[0.6348, 1.0453],
        [0.5090, 0.9195]])

In [24]:
a = torch.ones(2, 1, 1, 3)
b = torch.ones(4, 2, 3)

In [25]:
print(a)

tensor([[[[1., 1., 1.]]],


        [[[1., 1., 1.]]]])


In [26]:
print(b)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [30]:
c = a + b
print(c)

tensor([[[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]]])


In [31]:
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([2, 1, 1, 3])
torch.Size([4, 2, 3])
torch.Size([2, 4, 2, 3])


In [2]:
import torch

In [3]:
a = torch.rand(2, 2)
a = a * 10
print(a)

tensor([[8.1953, 8.5876],
        [5.8449, 7.6698]])


In [4]:
print(torch.floor(a))

tensor([[8., 8.],
        [5., 7.]])


In [5]:
print(torch.ceil(a))

tensor([[9., 9.],
        [6., 8.]])


In [6]:
print(torch.round(a))

tensor([[8., 9.],
        [6., 8.]])


In [7]:
print(torch.trunc(a))

tensor([[8., 8.],
        [5., 7.]])


In [8]:
print(torch.frac(a))

tensor([[0.1953, 0.5876],
        [0.8449, 0.6698]])


In [9]:
print(a % 2)

tensor([[0.1953, 0.5876],
        [1.8449, 1.6698]])


In [10]:
b = torch.tensor([[2, 3], [4, 5]],
                 dtype=torch.float)
print(torch.fmod(a, b))

tensor([[0.1953, 2.5876],
        [1.8449, 2.6698]])


In [11]:
print(torch.remainder(a, b))

tensor([[0.1953, 2.5876],
        [1.8449, 2.6698]])


In [14]:
a = torch.tensor([9, 9, 3])

In [15]:
print(a % 2)

tensor([1, 1, 1])


In [21]:
a = torch.tensor([-1, -9, -3])

In [22]:
print(a % 24)

tensor([23, 15, 21])


In [24]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.5653, 0.4631, 0.8969],
        [0.5166, 0.5791, 0.2122]])
tensor([[0.3371, 0.6739, 0.0503],
        [0.1214, 0.8646, 0.5509]])


In [25]:
print(torch.eq(a, b))

tensor([[False, False, False],
        [False, False, False]])


In [26]:
print(torch.equal(a, b))

False


In [27]:
print(torch.ge(a, b))

tensor([[ True, False,  True],
        [ True, False, False]])


In [28]:
print(torch.gt(a, b))

tensor([[ True, False,  True],
        [ True, False, False]])


In [29]:
print(torch.le(a, b))

tensor([[False,  True, False],
        [False,  True,  True]])


In [30]:
print(torch.lt(a, b))

tensor([[False,  True, False],
        [False,  True,  True]])


In [31]:
print(torch.ne(a, b))

tensor([[True, True, True],
        [True, True, True]])


In [32]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)

torch.Size([2, 5])


In [33]:
print(torch.sort(a, dim=1,descending=False))

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))


In [35]:
##topk
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])


In [36]:
print(a)

tensor([[2, 4, 3, 1, 5],
        [2, 3, 5, 1, 4]])


In [42]:
print(a.shape)

torch.Size([2, 5])


In [45]:
print(torch.topk(a, k=1, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4]]),
indices=tensor([[0, 1, 0, 0, 1]]))


In [47]:
print(torch.topk(a, k=2, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4],
        [2, 4, 5, 1, 5]]),
indices=tensor([[0, 1, 0, 0, 1],
        [1, 0, 1, 1, 0]]))


In [48]:
print(torch.topk(a, k=1, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1],
        [1]]),
indices=tensor([[3],
        [3]]))


In [49]:
print(torch.topk(a, k=2, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1, 2],
        [1, 2]]),
indices=tensor([[3, 0],
        [3, 0]]))


In [50]:
print(torch.kthvalue(a, k=1, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 3, 3, 1, 4]),
indices=tensor([0, 1, 0, 0, 1]))


In [39]:
print(torch.kthvalue(a, k=2, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))


In [51]:
print(torch.kthvalue(a, k=1, dim=1))

torch.return_types.kthvalue(
values=tensor([1, 1]),
indices=tensor([3, 3]))


In [52]:
print(torch.kthvalue(a, k=2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


In [54]:
a = torch.rand(2, 3)
print(a)
print(torch.isfinite(a))

tensor([[0.1759, 0.4719, 0.3270],
        [0.8196, 0.4423, 0.7999]])
tensor([[True, True, True],
        [True, True, True]])


In [55]:
print(a/0)
print(torch.isfinite(a/0))

tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[False, False, False],
        [False, False, False]])


In [56]:
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [57]:
import numpy as np
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([False, False,  True])


In [58]:
a = torch.rand(2, 3)
print(a)
print(torch.topk(a, k=2, dim=1, largest=False))
print(torch.topk(a, k=2, dim=1, largest=True))

tensor([[0.6403, 0.6641, 0.6821],
        [0.3130, 0.8222, 0.7762]])
torch.return_types.topk(
values=tensor([[0.6403, 0.6641],
        [0.3130, 0.7762]]),
indices=tensor([[0, 1],
        [0, 2]]))
torch.return_types.topk(
values=tensor([[0.6821, 0.6641],
        [0.8222, 0.7762]]),
indices=tensor([[2, 1],
        [1, 2]]))


In [59]:
import torch

In [60]:
a = torch.zeros(2, 3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# torch.cos()
# torch.cosh()
# torch.sin()
# torch.sinh()
# torch.tan()
# torch.tanh()
# torch.asin()
# torch.acos()
# torch.atan()
# torch.atan2()

In [ ]:
# torch.abs()
# torch.erf()
# torch.erfinv()
# torch.sigmoid()
# torch.neg()
# torch.reciprocal()
# torch.rsqrt()
# torch.sign()
# torch.lerp()
# torch.addcdiv()
# torch.addcmul()
# torch.cumprod()
# torch.cumsum()

In [74]:
a = torch.rand(2, 2)
print(torch.mean(a))
print(torch.mode(a))
print(torch.std(a))
print(torch.var(a))

tensor(0.6781)
torch.return_types.mode(
values=tensor([0.8037, 0.0068]),
indices=tensor([1, 0]))
tensor(0.4541)
tensor(0.2062)


In [66]:
# a = torch.rand(2, 2)
a = torch.ones(3, 5) * 3
print(a)
print(torch.mean(a, dim=0))
print(torch.sum(a, dim=0))
print(torch.prod(a, dim=0))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([3., 3., 3., 3., 3.])
tensor([9., 9., 9., 9., 9.])
tensor([27., 27., 27., 27., 27.])


In [67]:
print(torch.argmax(a, dim=0))
print(torch.argmin(a, dim=0))

tensor([0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0])


In [69]:
print(torch.median(a))
print(torch.mode(a))

tensor(3.)
torch.return_types.mode(
values=tensor([3., 3., 3.]),
indices=tensor([4, 4, 4]))


In [70]:
a = torch.rand(2, 2) * 10
print(a)
print(torch.histc(a, 6, 0, 0))

tensor([[0.6756, 8.1443],
        [7.4363, 7.5717]])
tensor([1., 0., 0., 0., 0., 3.])


In [76]:
a = torch.randint(0, 10, [10])
print(a)

tensor([7, 3, 8, 6, 4, 9, 5, 2, 0, 5])


In [77]:
print(torch.bincount(a))

tensor([1, 0, 1, 1, 1, 2, 1, 1, 1, 1])


In [2]:
import torch

In [3]:
torch.manual_seed(8)

In [7]:
mean = torch.rand(1, 2)
std = torch.rand(1, 2 )
print(torch.normal(mean, std))

tensor([[0.4469, 0.0508]])


In [10]:
import torch

a = torch.rand(2, 1)
b = torch.rand(2, 1)
print(a)
print(b)

tensor([[0.1713],
        [0.5103]])
tensor([[0.1068],
        [0.5911]])


In [11]:
print(torch.dist(a, b, p = 1))
print(torch.dist(a, b, p = 2))
print(torch.dist(a, b, p = 3))

tensor(0.1453)
tensor(0.1034)
tensor(0.0927)


In [13]:
print(torch.norm(a))
print(torch.norm(a, p=2))
print(torch.norm(a, p=3))
print(torch.norm(a, p='fro'))

tensor(0.5383)
tensor(0.5383)
tensor(0.5167)
tensor(0.5383)


In [1]:
import torch

In [3]:
a = torch.rand(2, 2) * 10
print(a)

tensor([[6.3217, 2.3548],
        [8.3811, 5.2546]])


In [4]:
a = a.clamp(2, 5)
print(a)

tensor([[5.0000, 2.3548],
        [5.0000, 5.0000]])


In [ ]:
# torch.where()
# torch.gather()
# torch.index_selet()
# torch.masked_select()
# torch.take()
# torch.nonzero()

In [6]:
import torch

#torch.where
a = torch.rand(4, 4)
print(a)
b = torch.rand(4, 4)
print(b)

out = torch.where(a > 0.5, a, b)
print(out)
# out = a if a > 0.5 else b

tensor([[0.6801, 0.3814, 0.6321, 0.8278],
        [0.3391, 0.5692, 0.8566, 0.9669],
        [0.0976, 0.4206, 0.2373, 0.5436],
        [0.8467, 0.0771, 0.9216, 0.3825]])
tensor([[0.8120, 0.7448, 0.8969, 0.2570],
        [0.3039, 0.2163, 0.5372, 0.9219],
        [0.2594, 0.3757, 0.8861, 0.1623],
        [0.1943, 0.3985, 0.4179, 0.1061]])
tensor([[0.6801, 0.7448, 0.6321, 0.8278],
        [0.3039, 0.5692, 0.8566, 0.9669],
        [0.2594, 0.3757, 0.8861, 0.5436],
        [0.8467, 0.3985, 0.9216, 0.1061]])


In [7]:
#torch.index_select
a = torch.rand(4, 4)
print(a)
out = torch.index_select(a, dim=0, index=torch.tensor([0, 3, 2]))
print(out, out.shape)

tensor([[0.8310, 0.8263, 0.6033, 0.5769],
        [0.0020, 0.1022, 0.0469, 0.9556],
        [0.6445, 0.2349, 0.3023, 0.4166],
        [0.3269, 0.6035, 0.3790, 0.7647]])
tensor([[0.8310, 0.8263, 0.6033, 0.5769],
        [0.3269, 0.6035, 0.3790, 0.7647],
        [0.6445, 0.2349, 0.3023, 0.4166]]) torch.Size([3, 4])


In [8]:
#torch.gather
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)

out = torch.gather(a, dim=0, index=torch.tensor([[0, 1, 1, 1],
                                 [0, 1, 2, 2],
                                 [0, 1, 3, 3]]))
print(out)
print(out.shape)

#dim=0, out[i, j, k] = input[index[i, j, k], j, k]
#dim=1, out[i, j, k] = input[i, index[i, j, k], k]
#dim=2, out[i, j, k] = input[i, j, index[i, j, k]]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])
torch.Size([3, 4])


In [10]:
#torch.masked_index
a = torch.linspace(1, 16, 16).view(4, 4)
mask = torch.gt(a, 8)
print(a)
print(mask)
out = torch.masked_select(a, mask)
print(out)

out2 = torch.masked_select(a, torch.lt(a, 8))
print(out2)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])
tensor([1., 2., 3., 4., 5., 6., 7.])


In [11]:
#torch.take
a = torch.linspace(1, 16, 16).view(4, 4)
b = torch.take(a, index=torch.tensor([0, 15, 13, 10]))
print(b)

tensor([ 1., 16., 14., 11.])


In [12]:
#torch.nonzero
print("torch.take")
a = torch.tensor([[0, 1, 2, 0], [2, 3, 0, 1]])
out = torch.nonzero(a)
print(out)
#稀疏表示

torch.take
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])


In [1]:
import torch

In [2]:
a = torch.zeros((2, 4))
b = torch.ones((2, 4))

out = torch.cat((a,b),dim=0)
print(out)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
out = torch.cat((a,b),dim=1)
print(out)

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])


In [5]:
a = torch.linspace(1, 6, 6).view(2, 3)
print(a)
b = torch.linspace(7, 12, 6).view(2, 3)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
out = torch.stack((a, b), dim=0)
print(out)
print(out.shape)
print(out[:, :, 0])
print(out[:, :, 1])

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[ 1.,  4.],
        [ 7., 10.]])
tensor([[ 2.,  5.],
        [ 8., 11.]])


In [10]:
out = torch.stack((a, b), dim=1)
print(out)
print(out.shape)
print(out[:, :, 0])
print(out[:, :, 1])

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[ 1.,  7.],
        [ 4., 10.]])
tensor([[ 2.,  8.],
        [ 5., 11.]])


In [7]:
import torch

a = torch.rand((3, 4))
print(a)

tensor([[0.7895, 0.7579, 0.7310, 0.9536],
        [0.3461, 0.8756, 0.9622, 0.5282],
        [0.6633, 0.3030, 0.3778, 0.5130]])


In [8]:
out = torch.chunk(a, 2, dim=0)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.7895, 0.7579, 0.7310, 0.9536],
        [0.3461, 0.8756, 0.9622, 0.5282]]) torch.Size([2, 4])
tensor([[0.6633, 0.3030, 0.3778, 0.5130]]) torch.Size([1, 4])


In [9]:
a = torch.rand((10, 4))
print(a)
out = torch.split(a, 3, dim=0)
print(len(out))
for t in out:
    print(t, t.shape)

tensor([[2.5896e-01, 8.0512e-01, 9.4159e-01, 3.7121e-01],
        [7.0735e-01, 1.0398e-01, 3.4312e-01, 3.3424e-01],
        [2.4163e-02, 7.9617e-01, 7.0598e-02, 8.5369e-01],
        [9.8855e-01, 9.7997e-01, 8.7935e-01, 6.5079e-01],
        [4.4366e-01, 4.1438e-03, 7.6109e-01, 1.2500e-01],
        [6.3414e-01, 3.7920e-01, 7.7466e-01, 6.5705e-01],
        [8.0937e-01, 4.3453e-02, 9.1171e-01, 1.2555e-01],
        [8.3426e-02, 3.6500e-01, 3.9975e-01, 8.5957e-01],
        [9.1135e-01, 6.8242e-01, 7.6401e-01, 7.2906e-01],
        [1.2864e-02, 4.8685e-04, 1.4410e-02, 9.0254e-02]])
4
tensor([[0.2590, 0.8051, 0.9416, 0.3712],
        [0.7073, 0.1040, 0.3431, 0.3342],
        [0.0242, 0.7962, 0.0706, 0.8537]]) torch.Size([3, 4])
tensor([[0.9886, 0.9800, 0.8794, 0.6508],
        [0.4437, 0.0041, 0.7611, 0.1250],
        [0.6341, 0.3792, 0.7747, 0.6570]]) torch.Size([3, 4])
tensor([[0.8094, 0.0435, 0.9117, 0.1255],
        [0.0834, 0.3650, 0.3998, 0.8596],
        [0.9114, 0.6824, 0.7640, 0.7291]]

In [11]:
out = torch.split(a, [1, 3, 6], dim=0)
for t in out:
    print(t, t.shape)

tensor([[0.2590, 0.8051, 0.9416, 0.3712]]) torch.Size([1, 4])
tensor([[0.7073, 0.1040, 0.3431, 0.3342],
        [0.0242, 0.7962, 0.0706, 0.8537],
        [0.9886, 0.9800, 0.8794, 0.6508]]) torch.Size([3, 4])
tensor([[4.4366e-01, 4.1438e-03, 7.6109e-01, 1.2500e-01],
        [6.3414e-01, 3.7920e-01, 7.7466e-01, 6.5705e-01],
        [8.0937e-01, 4.3453e-02, 9.1171e-01, 1.2555e-01],
        [8.3426e-02, 3.6500e-01, 3.9975e-01, 8.5957e-01],
        [9.1135e-01, 6.8242e-01, 7.6401e-01, 7.2906e-01],
        [1.2864e-02, 4.8685e-04, 1.4410e-02, 9.0254e-02]]) torch.Size([6, 4])


In [12]:
import torch

a = torch.rand(2, 3)
print(a)

tensor([[0.1251, 0.1528, 0.6659],
        [0.2525, 0.9724, 0.9585]])


In [30]:
out = torch.reshape(a, (3, 2))
print(out)

tensor([[0.0216, 0.1757],
        [0.7152, 0.8142],
        [0.8837, 0.4949]])


In [31]:
print(torch.t(out))
print(torch.transpose(out, 0, 1))

tensor([[0.0216, 0.7152, 0.8837],
        [0.1757, 0.8142, 0.4949]])
tensor([[0.0216, 0.7152, 0.8837],
        [0.1757, 0.8142, 0.4949]])


In [25]:
a = torch.rand(1, 2, 3)
out = torch.transpose(a, 0, 1)
print(out)
print(out.shape)

tensor([[[0.0216, 0.1757, 0.7152]],

        [[0.8142, 0.8837, 0.4949]]])
torch.Size([2, 1, 3])


In [26]:
out = torch.squeeze(a)
print(out)
print(out.shape)

tensor([[0.0216, 0.1757, 0.7152],
        [0.8142, 0.8837, 0.4949]])
torch.Size([2, 3])


In [27]:
print(a)

tensor([[[0.0216, 0.1757, 0.7152],
         [0.8142, 0.8837, 0.4949]]])


In [28]:
out = torch.unsqueeze(a, -1)
print(out)
print(out.shape)

tensor([[[[0.0216],
          [0.1757],
          [0.7152]],

         [[0.8142],
          [0.8837],
          [0.4949]]]])
torch.Size([1, 2, 3, 1])


In [19]:
out = torch.unbind(a, dim=2)
print(out)

(tensor([[0.9816, 0.2179]]), tensor([[0.1661, 0.2739]]), tensor([[0.7049, 0.9773]]))


In [20]:
print(a)
print(torch.flip(a, dims=[2, 1]))

tensor([[[0.9816, 0.1661, 0.7049],
         [0.2179, 0.2739, 0.9773]]])
tensor([[[0.9773, 0.2739, 0.2179],
         [0.7049, 0.1661, 0.9816]]])


In [29]:
print(a)
out = torch.rot90(a, -1, dims=[0, 2])
print(out)
print(out.shape)

tensor([[[0.0216, 0.1757, 0.7152],
         [0.8142, 0.8837, 0.4949]]])
tensor([[[0.0216],
         [0.8142]],

        [[0.1757],
         [0.8837]],

        [[0.7152],
         [0.4949]]])
torch.Size([3, 2, 1])


In [32]:
import torch

a = torch.full((2,3), 10)
print(a)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [1]:
import torch
import numpy as np

In [2]:
import cv2
data = cv2.imread("/Users/linghuang/Git/Deep-Learning/Pytorch/03/test.png")
print(data)

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]]


In [3]:
# cv2.imshow("test1", data)
# cv2.waitKey(0)

In [4]:
# a = np.zeros([2, 2])
# out = torch.from_numpy(a)

out = torch.from_numpy(data)
out = torch.flip(out, dims=[0])
data = out.numpy()
print(data)

# out = out.to(torch.device("cuda"))
# print(out.is_cuda)

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]]


In [5]:
out = torch.flip(out, dims=[0])

out = out.to(torch.device("cpu"))
# out = out.to(torch.device("cuda"))

print(out.is_cuda)

data = out.numpy()

# cv2.imshow("test2", data)

# cv2.waitKey(0)

False


### Variable (autograd)

### nn.Module