In [1]:
import torch
import numpy as np

### Tensor

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

- Scalar is a single number.
- Vector is an array of numbers.
- Matrix is a 2-D array of numbers.
- Tensors are N-D arrays of numbers.

In [3]:
np.array([0.0, 0.1, 0.3])
torch.tensor([0.0, 0.1, 0.2])

tensor([0.0000, 0.1000, 0.2000])

In [4]:
x = np.array([0.0, 0.1, 0.3])
torch.from_numpy(x)

tensor([0.0000, 0.1000, 0.3000], dtype=torch.float64)

In [6]:
np.ones(3)
torch.ones(3)

tensor([1., 1., 1.])

In [8]:
np.zeros(5)
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [10]:
np.ones(10)
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.eye(3)
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
np.arange(1,5,2)
torch.arange(1,5,2)

tensor([1, 3])

In [17]:
np.linspace(1,5,2)
torch.linspace(1,5,2)

tensor([1., 5.])

In [44]:
d = torch.zeros(2,3)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [45]:
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [22]:
np.random.rand(3,2)
torch.rand(2, 3)

tensor([[0.8632, 0.7223, 0.5323],
        [0.7446, 0.9398, 0.8634]])

In [48]:
d = torch.Tensor(2, 2).uniform_(-1, 1)
print(d)
print(d.type())

tensor([[ 0.4829,  0.4955],
        [-0.3262, -0.1285]])
torch.FloatTensor


In [27]:
# standard normal
np.random.randn(2, 4)
torch.randn(2,4)

tensor([[ 0.4851, -0.0987,  1.6798, -0.2318],
        [-0.2457,  0.3351,  0.5537, -0.1356]])

In [31]:
np.random.normal(0, 0.1, 10)
torch.normal(0, 0.1, size=(1, 10))

tensor([[ 0.0085, -0.0321,  0.0395,  0.1118,  0.0580, -0.0725,  0.0073, -0.0383,
         -0.0826,  0.1012]])

In [37]:
np.random.uniform(0, 1, 10)
torch.distributions.Uniform(low=0, high=1)

Uniform(low: 0.0, high: 1.0)

In [39]:
np.random.permutation(10)
torch.randperm(10)

tensor([9, 0, 1, 6, 4, 3, 5, 8, 2, 7])

In [54]:
torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

tensor([1., 2., 3.])

In [53]:
indices = torch.tensor([[0,1,1], [2,0,2]])
values = torch.tensor([2,3,4], dtype=torch.float32)
x = torch.sparse_coo_tensor(indices,values, [2, 4])
print(x)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([2., 3., 4.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)


In [2]:
a = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [3]:
b = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [4]:
c = a + b
print(c)

tensor([2., 4., 6.])


In [6]:
c = torch.sub(a, b)
print(c)

tensor([0., 0., 0.])


In [7]:
a.sub(b)
print(a)

tensor([1., 2., 3.])


In [8]:
a.sub_(b)
print(a)

tensor([0., 0., 0.])


In [10]:
d = b * c
print(d)

tensor([0., 0., 0.])


In [11]:
d = torch.mul(b, c)
print(d)

tensor([0., 0., 0.])


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
a.mul(b)

tensor([1, 4, 9])

In [13]:
a.mul_(b)

tensor([1, 4, 9])

In [14]:
print(a)

tensor([1, 4, 9])


In [16]:
c = a / b
print(c)

tensor([1., 2., 3.])


In [19]:
c = torch.div(a, b)
print(c)

tensor([1., 2., 3.])


In [20]:
a.div(b)

tensor([1., 2., 3.])

In [23]:
b

tensor([1, 2, 3])

In [27]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
b = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
a.div_(b)

tensor([1., 1., 1.])

Matrix computation

In [28]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [29]:
print(torch.mm(a, b))
print(torch.matmul(a, b))
print(a @ b)
print(a.mm(b))
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


对于高维的tensor， 矩阵乘法作用于最后两个维度

In [30]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(torch.matmul(a, b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [35]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
print(a)
print(torch.pow(a, 2))
print(a.pow(2))
print(a**2)
print(a.pow_(2))
print(a)

tensor([1., 2., 3.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])


In [36]:
print(torch.exp(a))
b = a.exp_()
print(b)

tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])


In [38]:
print(a)
print(torch.sqrt(a))
print(a.sqrt())
print(a.sqrt_())
print(a)

tensor([ 1.6487,  7.3891, 90.0171])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])


In [39]:
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))
print(torch.log_(a))
print(a)

tensor([0.3607, 1.4427, 3.2461])
tensor([0.1086, 0.4343, 0.9772])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])


### Variable (autograd)

### nn.Module