In [1]:
import torch
import numpy as np

### Tensor

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

- Scalar is a single number.
- Vector is an array of numbers.
- Matrix is a 2-D array of numbers.
- Tensors are N-D arrays of numbers.

In [3]:
np.array([0.0, 0.1, 0.3])
torch.tensor([0.0, 0.1, 0.2])

tensor([0.0000, 0.1000, 0.2000])

In [4]:
x = np.array([0.0, 0.1, 0.3])
torch.from_numpy(x)

tensor([0.0000, 0.1000, 0.3000], dtype=torch.float64)

In [6]:
np.ones(3)
torch.ones(3)

tensor([1., 1., 1.])

In [8]:
np.zeros(5)
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [10]:
np.ones(10)
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.eye(3)
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
np.arange(1,5,2)
torch.arange(1,5,2)

tensor([1, 3])

In [17]:
np.linspace(1,5,2)
torch.linspace(1,5,2)

tensor([1., 5.])

In [44]:
d = torch.zeros(2,3)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [45]:
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [22]:
np.random.rand(3,2)
torch.rand(2, 3)

tensor([[0.8632, 0.7223, 0.5323],
        [0.7446, 0.9398, 0.8634]])

In [48]:
d = torch.Tensor(2, 2).uniform_(-1, 1)
print(d)
print(d.type())

tensor([[ 0.4829,  0.4955],
        [-0.3262, -0.1285]])
torch.FloatTensor


In [27]:
# standard normal
np.random.randn(2, 4)
torch.randn(2,4)

tensor([[ 0.4851, -0.0987,  1.6798, -0.2318],
        [-0.2457,  0.3351,  0.5537, -0.1356]])

In [31]:
np.random.normal(0, 0.1, 10)
torch.normal(0, 0.1, size=(1, 10))

tensor([[ 0.0085, -0.0321,  0.0395,  0.1118,  0.0580, -0.0725,  0.0073, -0.0383,
         -0.0826,  0.1012]])

In [37]:
np.random.uniform(0, 1, 10)
torch.distributions.Uniform(low=0, high=1)

Uniform(low: 0.0, high: 1.0)

In [39]:
np.random.permutation(10)
torch.randperm(10)

tensor([9, 0, 1, 6, 4, 3, 5, 8, 2, 7])

In [54]:
torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

tensor([1., 2., 3.])

In [53]:
indices = torch.tensor([[0,1,1], [2,0,2]])
values = torch.tensor([2,3,4], dtype=torch.float32)
x = torch.sparse_coo_tensor(indices,values, [2, 4])
print(x)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([2., 3., 4.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)


In [2]:
a = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [3]:
b = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [4]:
c = a + b
print(c)

tensor([2., 4., 6.])


In [6]:
c = torch.sub(a, b)
print(c)

tensor([0., 0., 0.])


In [7]:
a.sub(b)
print(a)

tensor([1., 2., 3.])


In [8]:
a.sub_(b)
print(a)

tensor([0., 0., 0.])


In [10]:
d = b * c
print(d)

tensor([0., 0., 0.])


In [11]:
d = torch.mul(b, c)
print(d)

tensor([0., 0., 0.])


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
a.mul(b)

tensor([1, 4, 9])

In [13]:
a.mul_(b)

tensor([1, 4, 9])

In [14]:
print(a)

tensor([1, 4, 9])


In [16]:
c = a / b
print(c)

tensor([1., 2., 3.])


In [19]:
c = torch.div(a, b)
print(c)

tensor([1., 2., 3.])


In [20]:
a.div(b)

tensor([1., 2., 3.])

In [23]:
b

tensor([1, 2, 3])

In [27]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
b = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
a.div_(b)

tensor([1., 1., 1.])

Matrix computation

In [28]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [29]:
print(torch.mm(a, b))
print(torch.matmul(a, b))
print(a @ b)
print(a.mm(b))
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


对于高维的tensor， 矩阵乘法作用于最后两个维度

In [30]:
a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a.matmul(b))
print(torch.matmul(a, b))

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [35]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
print(a)
print(torch.pow(a, 2))
print(a.pow(2))
print(a**2)
print(a.pow_(2))
print(a)

tensor([1., 2., 3.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])


In [36]:
print(torch.exp(a))
b = a.exp_()
print(b)

tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])


In [38]:
print(a)
print(torch.sqrt(a))
print(a.sqrt())
print(a.sqrt_())
print(a)

tensor([ 1.6487,  7.3891, 90.0171])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])
tensor([1.2840, 2.7183, 9.4877])


In [39]:
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))
print(torch.log_(a))
print(a)

tensor([0.3607, 1.4427, 3.2461])
tensor([0.1086, 0.4343, 0.9772])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])
tensor([0.2500, 1.0000, 2.2500])


In [2]:
a = torch.rand(2, 3)
b = torch.rand(3)

In [3]:
print(a)

tensor([[0.6836, 0.2217, 0.8508],
        [0.2915, 0.6192, 0.0198]])


In [11]:
print(a.shape)

torch.Size([2, 3])


In [4]:
print(b)

tensor([0.3733, 0.7068, 0.8890])


In [12]:
print(b.shape)

torch.Size([3])


In [5]:
c = a + b

In [6]:
print(c)

tensor([[1.0569, 0.9284, 1.7398],
        [0.6648, 1.3259, 0.9088]])


In [13]:
a = torch.rand(2, 1)
b = torch.rand(2)

In [15]:
print(a)

tensor([[0.6062],
        [0.4804]])


In [16]:
print(b)

tensor([0.0286, 0.4391])


In [14]:
a + b

tensor([[0.6348, 1.0453],
        [0.5090, 0.9195]])

In [24]:
a = torch.ones(2, 1, 1, 3)
b = torch.ones(4, 2, 3)

In [25]:
print(a)

tensor([[[[1., 1., 1.]]],


        [[[1., 1., 1.]]]])


In [26]:
print(b)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [30]:
c = a + b
print(c)

tensor([[[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]]])


In [31]:
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([2, 1, 1, 3])
torch.Size([4, 2, 3])
torch.Size([2, 4, 2, 3])


In [2]:
import torch

In [3]:
a = torch.rand(2, 2)
a = a * 10
print(a)

tensor([[8.1953, 8.5876],
        [5.8449, 7.6698]])


In [4]:
print(torch.floor(a))

tensor([[8., 8.],
        [5., 7.]])


In [5]:
print(torch.ceil(a))

tensor([[9., 9.],
        [6., 8.]])


In [6]:
print(torch.round(a))

tensor([[8., 9.],
        [6., 8.]])


In [7]:
print(torch.trunc(a))

tensor([[8., 8.],
        [5., 7.]])


In [8]:
print(torch.frac(a))

tensor([[0.1953, 0.5876],
        [0.8449, 0.6698]])


In [9]:
print(a % 2)

tensor([[0.1953, 0.5876],
        [1.8449, 1.6698]])


In [10]:
b = torch.tensor([[2, 3], [4, 5]],
                 dtype=torch.float)
print(torch.fmod(a, b))

tensor([[0.1953, 2.5876],
        [1.8449, 2.6698]])


In [11]:
print(torch.remainder(a, b))

tensor([[0.1953, 2.5876],
        [1.8449, 2.6698]])


In [14]:
a = torch.tensor([9, 9, 3])

In [15]:
print(a % 2)

tensor([1, 1, 1])


In [21]:
a = torch.tensor([-1, -9, -3])

In [22]:
print(a % 24)

tensor([23, 15, 21])


In [24]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.5653, 0.4631, 0.8969],
        [0.5166, 0.5791, 0.2122]])
tensor([[0.3371, 0.6739, 0.0503],
        [0.1214, 0.8646, 0.5509]])


In [25]:
print(torch.eq(a, b))

tensor([[False, False, False],
        [False, False, False]])


In [26]:
print(torch.equal(a, b))

False


In [27]:
print(torch.ge(a, b))

tensor([[ True, False,  True],
        [ True, False, False]])


In [28]:
print(torch.gt(a, b))

tensor([[ True, False,  True],
        [ True, False, False]])


In [29]:
print(torch.le(a, b))

tensor([[False,  True, False],
        [False,  True,  True]])


In [30]:
print(torch.lt(a, b))

tensor([[False,  True, False],
        [False,  True,  True]])


In [31]:
print(torch.ne(a, b))

tensor([[True, True, True],
        [True, True, True]])


In [32]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)

torch.Size([2, 5])


In [33]:
print(torch.sort(a, dim=1,descending=False))

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))


In [35]:
##topk
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])


In [36]:
print(a)

tensor([[2, 4, 3, 1, 5],
        [2, 3, 5, 1, 4]])


In [42]:
print(a.shape)

torch.Size([2, 5])


In [45]:
print(torch.topk(a, k=1, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4]]),
indices=tensor([[0, 1, 0, 0, 1]]))


In [47]:
print(torch.topk(a, k=2, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4],
        [2, 4, 5, 1, 5]]),
indices=tensor([[0, 1, 0, 0, 1],
        [1, 0, 1, 1, 0]]))


In [48]:
print(torch.topk(a, k=1, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1],
        [1]]),
indices=tensor([[3],
        [3]]))


In [49]:
print(torch.topk(a, k=2, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1, 2],
        [1, 2]]),
indices=tensor([[3, 0],
        [3, 0]]))


In [50]:
print(torch.kthvalue(a, k=1, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 3, 3, 1, 4]),
indices=tensor([0, 1, 0, 0, 1]))


In [39]:
print(torch.kthvalue(a, k=2, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))


In [51]:
print(torch.kthvalue(a, k=1, dim=1))

torch.return_types.kthvalue(
values=tensor([1, 1]),
indices=tensor([3, 3]))


In [52]:
print(torch.kthvalue(a, k=2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


In [54]:
a = torch.rand(2, 3)
print(a)
print(torch.isfinite(a))

tensor([[0.1759, 0.4719, 0.3270],
        [0.8196, 0.4423, 0.7999]])
tensor([[True, True, True],
        [True, True, True]])


In [55]:
print(a/0)
print(torch.isfinite(a/0))

tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[False, False, False],
        [False, False, False]])


In [56]:
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [57]:
import numpy as np
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([False, False,  True])


In [58]:
a = torch.rand(2, 3)
print(a)
print(torch.topk(a, k=2, dim=1, largest=False))
print(torch.topk(a, k=2, dim=1, largest=True))

tensor([[0.6403, 0.6641, 0.6821],
        [0.3130, 0.8222, 0.7762]])
torch.return_types.topk(
values=tensor([[0.6403, 0.6641],
        [0.3130, 0.7762]]),
indices=tensor([[0, 1],
        [0, 2]]))
torch.return_types.topk(
values=tensor([[0.6821, 0.6641],
        [0.8222, 0.7762]]),
indices=tensor([[2, 1],
        [1, 2]]))


In [59]:
import torch

In [60]:
a = torch.zeros(2, 3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# torch.cos()
# torch.cosh()
# torch.sin()
# torch.sinh()
# torch.tan()
# torch.tanh()
# torch.asin()
# torch.acos()
# torch.atan()
# torch.atan2()

In [ ]:
# torch.abs()
# torch.erf()
# torch.erfinv()
# torch.sigmoid()
# torch.neg()
# torch.reciprocal()
# torch.rsqrt()
# torch.sign()
# torch.lerp()
# torch.addcdiv()
# torch.addcmul()
# torch.cumprod()
# torch.cumsum()

In [74]:
a = torch.rand(2, 2)
print(torch.mean(a))
print(torch.mode(a))
print(torch.std(a))
print(torch.var(a))

tensor(0.6781)
torch.return_types.mode(
values=tensor([0.8037, 0.0068]),
indices=tensor([1, 0]))
tensor(0.4541)
tensor(0.2062)


In [66]:
# a = torch.rand(2, 2)
a = torch.ones(3, 5) * 3
print(a)
print(torch.mean(a, dim=0))
print(torch.sum(a, dim=0))
print(torch.prod(a, dim=0))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([3., 3., 3., 3., 3.])
tensor([9., 9., 9., 9., 9.])
tensor([27., 27., 27., 27., 27.])


In [67]:
print(torch.argmax(a, dim=0))
print(torch.argmin(a, dim=0))

tensor([0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0])


In [69]:
print(torch.median(a))
print(torch.mode(a))

tensor(3.)
torch.return_types.mode(
values=tensor([3., 3., 3.]),
indices=tensor([4, 4, 4]))


In [70]:
a = torch.rand(2, 2) * 10
print(a)
print(torch.histc(a, 6, 0, 0))

tensor([[0.6756, 8.1443],
        [7.4363, 7.5717]])
tensor([1., 0., 0., 0., 0., 3.])


In [76]:
a = torch.randint(0, 10, [10])
print(a)

tensor([7, 3, 8, 6, 4, 9, 5, 2, 0, 5])


In [77]:
print(torch.bincount(a))

tensor([1, 0, 1, 1, 1, 2, 1, 1, 1, 1])


In [2]:
import torch

In [3]:
torch.manual_seed(8)

In [7]:
mean = torch.rand(1, 2)
std = torch.rand(1, 2 )
print(torch.normal(mean, std))

tensor([[0.4469, 0.0508]])


In [10]:
import torch

a = torch.rand(2, 1)
b = torch.rand(2, 1)
print(a)
print(b)

tensor([[0.1713],
        [0.5103]])
tensor([[0.1068],
        [0.5911]])


In [11]:
print(torch.dist(a, b, p = 1))
print(torch.dist(a, b, p = 2))
print(torch.dist(a, b, p = 3))

tensor(0.1453)
tensor(0.1034)
tensor(0.0927)


In [13]:
print(torch.norm(a))
print(torch.norm(a, p=2))
print(torch.norm(a, p=3))
print(torch.norm(a, p='fro'))

tensor(0.5383)
tensor(0.5383)
tensor(0.5167)
tensor(0.5383)


### Variable (autograd)

### nn.Module