In [1]:
import torch
from torchvision import datasets, transforms

# Define transformations to apply to the data
transform = transforms.Compose([
    transforms.ToTensor()  # Convert image to tensor)
])

# Download and load the MNIST training dataset
train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True, )

# Create a data loader for the training dataset
train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)

# Iterate over the data loader in batches
for images, labels in train_dataloader:
    # `images` is a batch of input images
    # `labels` is a batch of corresponding labels

    # Display the input tensor
    print("Batch shape:", images.shape)
    print("Batch tensor:")
    print(images)
    break # Added to stop at the first iteration
    # The output shows that we have 64 images in 1 batch. Each image in the batch is a represented as a 1 chanelled 28x28 tensor.

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9912422/9912422 [00:00<00:00, 14712514.16it/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 2659400.52it/s]

Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden




100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1648877/1648877 [00:00<00:00, 18355104.65it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 815135.37it/s]


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

Batch shape: torch.Size([64, 1, 28, 28])
Batch tensor:
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],


In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

# Step 1: Prepare the data
# Define the number of features (input size)
input_size = 2

# Define the number of classes (output size)
output_size = 2

# Create the training dataset
# Create the training dataset
X_train = torch.tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [5.0, 1.0]])
y_train = torch.tensor([0, 1, 0, 1])  # Numerical labels: 0 for 'dog', 1 for 'cat'

In [5]:
# Step 2: Define the logistic regression model
class LogisticRegressionModel(nn.Module):
    def __init__(self):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

model = LogisticRegressionModel()

In [6]:
# Step 3: Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()  # Fill in the blank for the appropriate loss function
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Fill in the blank for the appropriate optimizer

In [7]:
# Step 4: Train the model
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)  # Fill in the blanks for the appropriate y_train values

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [100/1000], Loss: 0.6941
Epoch [200/1000], Loss: 0.6932
Epoch [300/1000], Loss: 0.6924
Epoch [400/1000], Loss: 0.6916
Epoch [500/1000], Loss: 0.6908
Epoch [600/1000], Loss: 0.6900
Epoch [700/1000], Loss: 0.6892
Epoch [800/1000], Loss: 0.6885
Epoch [900/1000], Loss: 0.6877
Epoch [1000/1000], Loss: 0.6870


In [8]:
# Step 5: Test the model
X_test = torch.tensor([[4.0, 3.0]])
predicted = model(X_test)

predicted_class = torch.argmax(predicted).item()
print("Predicted class:", predicted_class)  # Fill in the blank for the appropriate tensor to get the predicted class

Predicted class: 0


 Implementing Single-Headed Attention with einsum

In this coding question, you will implement a single-headed attention function using einsum in PyTorch. The provided inspiration function demonstrates the computation of single-headed attention without using einsum. Your task is to take inspiration from the given function and write a new function that performs the same computation using einsum. Explanation of the code without Einsum: Inputs:

query: A PyTorch tensor of shape (batch_size, sequence_length, query_dim). This tensor represents the query vectors for each token in the sequence. key: A PyTorch tensor of shape (batch_size, sequence_length, key_dim). This tensor represents the key vectors for each token in the sequence. value: A PyTorch tensor of shape (batch_size, sequence_length, value_dim). This tensor represents the value vectors for each token in the sequence. Outputs:

attended_values: A PyTorch tensor of shape (batch_size, sequence_length, value_dim). This tensor represents the attended values obtained by combining the value vectors with the attention weights. attention_weights: A PyTorch tensor of shape (batch_size, sequence_length, sequence_length). This tensor contains the attention weights indicating the importance of each token's value in producing the attended values.

In [11]:
import torch.nn.functional as F

In [12]:
def single_head_attention(query, key, value):
    # Calculate the dot product between query and key
    dot_product = torch.matmul(query, key.transpose(-2, -1))

    # Scale the dot product by dividing it by the square root of the dimension of the key vector
    scaled_dot_product = dot_product / (key.size(-1) ** 0.5)

    # Apply softmax to obtain attention weights along the last dimension (head dimension)
    attention_weights = F.softmax(scaled_dot_product, dim=-1)

    # Compute the weighted sum of value vectors
    attended_values = torch.matmul(attention_weights, value)

    return attended_values, attention_weights

# Example usage
batch_size = 2
seq_len = 3
dim = 4

query = torch.randn(batch_size, seq_len, dim)
key = torch.randn(batch_size, seq_len, dim)
value = torch.randn(batch_size, seq_len, dim)

attended_values, attention_weights = single_head_attention(query, key, value)

print("Attended Values:\n", attended_values)
print("Attention Weights:\n", attention_weights)

Attended Values:
 tensor([[[-0.2673,  0.2538,  0.5007, -0.4855],
         [-0.2617, -0.1164,  0.6346, -0.8367],
         [-0.7097, -1.1799,  0.4262,  0.1321]],

        [[ 0.8759, -0.0637,  0.0201,  0.2590],
         [ 0.8979, -1.2738,  0.9440, -1.4473],
         [ 0.7948, -0.1066,  0.0878,  0.1396]]])
Attention Weights:
 tensor([[[0.2914, 0.2136, 0.4950],
         [0.1226, 0.1950, 0.6824],
         [0.0946, 0.8311, 0.0743]],

        [[0.1815, 0.4412, 0.3773],
         [0.0372, 0.0210, 0.9419],
         [0.1994, 0.3889, 0.4117]]])


In [13]:
def single_head_attention_with_einsum(query, key, value):
    # Calculate the dot product between query and key
    dot_product = torch.einsum('bqd,bkd->bqk', query, key)

    # Scale the dot product by dividing it by the square root of the dimension of the key vector
    scaled_dot_product = dot_product / (key.size(-1) ** 0.5)

    # Apply softmax to obtain attention weights along the last dimension (head dimension)
    attention_weights = F.softmax(scaled_dot_product, dim=-1)

    # Compute the weighted sum of value vectors
    attended_values = torch.einsum('bqk,bvd->bqd', attention_weights, value)

    return attended_values, attention_weights

# Example usage
batch_size = 2
seq_len = 3
dim = 4

query = torch.randn(batch_size, seq_len, dim)
key = torch.randn(batch_size, seq_len, dim)
value = torch.randn(batch_size, seq_len, dim)

attended_values_einsum, attention_weights_einsum = single_head_attention_with_einsum(query, key, value)

print("Attended Values with Einsum:\n", attended_values_einsum)
print("Attention Weights with Einsum:\n", attention_weights_einsum)

Attended Values with Einsum:
 tensor([[[-2.3905, -1.5528,  0.7246, -2.8163],
         [-2.3905, -1.5528,  0.7246, -2.8163],
         [-2.3905, -1.5528,  0.7246, -2.8163]],

        [[-1.7983,  0.5002, -0.3163, -1.1031],
         [-1.7983,  0.5002, -0.3163, -1.1031],
         [-1.7983,  0.5002, -0.3163, -1.1031]]])
Attention Weights with Einsum:
 tensor([[[0.2882, 0.0807, 0.6311],
         [0.1343, 0.6147, 0.2509],
         [0.2829, 0.4953, 0.2218]],

        [[0.3522, 0.2891, 0.3587],
         [0.3270, 0.0651, 0.6079],
         [0.3017, 0.0621, 0.6362]]])
