Slide *13* : Creating Tensors in PyTorch

In [46]:
!pip install torch

In [47]:
import torch
# Create a 3-dimensional tensor with random values from a uniform distribution
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.5392, 0.0162, 0.3881, 0.0104],
         [0.6707, 0.1225, 0.0559, 0.4721],
         [0.6120, 0.4389, 0.8636, 0.8101]],

        [[0.0828, 0.9944, 0.0166, 0.5595],
         [0.4823, 0.7014, 0.6791, 0.2427],
         [0.0072, 0.7880, 0.4001, 0.8874]]])


Slide 15 : Identity Tensor

In [48]:
def identity_matrix_with_diag (n):
	tensor_ones = torch.ones (n, n) #
	# print(tensor_ones)
	# In the return statement, torch.diag converts the identity_tensor to one dimension
	# Using torch.diag again creates a 20 tensor from the 1D tensor
	return torch.diag(torch.diag(tensor_ones))

In [49]:
print(identity_matrix_with_diag(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [50]:
def identity_matrix_with_sum(n) :
	zeros_tensor = torch.zeros (n, n)
	identity_tensor = torch.diag(torch.ones (n)) # torch.diag changes 10 	to 2D tensor
	identity_matrix = zeros_tensor + identity_tensor # Element wise addition of 	two tensors
	return identity_matrix

In [51]:
print(identity_matrix_with_sum(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Slide 17: Basic Mathematical Operations on Tensors

In [52]:
import torch
# Create a base tensor
base_tensor = torch. tensor ([[1, 2], [3,4]])
# Create another tensor
second_tensor = torch.tensor ([[2, 2], [1,1]])
# Addition
addition_tensor = base_tensor + second_tensor
print("Addition: \\n", addition_tensor)
# Subtraction
subtraction_tensor = base_tensor - second_tensor
print("Subtraction: \\n", subtraction_tensor)
# Multiplication
multiplication_tensor = base_tensor * second_tensor
print("Multiplication: \\n", multiplication_tensor)
# Division
division_tensor = base_tensor / second_tensor
print("Division: In", division_tensor)


Addition: \n tensor([[3, 4],
        [4, 5]])
Subtraction: \n tensor([[-1,  0],
        [ 2,  3]])
Multiplication: \n tensor([[2, 4],
        [3, 4]])
Division: In tensor([[0.5000, 1.0000],
        [3.0000, 4.0000]])


Slide 18: Tensor indexing and slicing

In [53]:
import torch
# Create a tensor with size (2, 3, 3)
tensor = torch.tensor ([
	[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
	[[10, 11, 12], [13, 14, 15],[16, 17,18]]
])
print ("Original Tensor:")
print (tensor)
print("\\nTensor Shape:", tensor.shape)


Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
\nTensor Shape: torch.Size([2, 3, 3])


Slide 19 : Tensor indexing and slicing

In [54]:
# Row Slice (Slice of the second row)
row_slice = tensor[:, 1, :]
print("\\now Slice:")
print (row_slice)
print ("Row Slice Shape:", row_slice.shape)



\now Slice:
tensor([[ 4,  5,  6],
        [13, 14, 15]])
Row Slice Shape: torch.Size([2, 3])


Slide 20: Tensor indexing and slicing

In [55]:
# Column Slice (Slice of the third column)
column_slice = tensor[:,:, 2]
print ("\\nColumn Slice:")
print(column_slice)
print ("Column Slice Shape:", column_slice.shape)


\nColumn Slice:
tensor([[ 3,  6,  9],
        [12, 15, 18]])
Column Slice Shape: torch.Size([2, 3])


Slide 21 : Tensor Indexing and Slicing

In [56]:
# Mixed Slice (Mixed slice of rows and columns)
mixed_slice = tensor[:, 0:2, 1:3]
print("\\nMixed Slice:")
print (mixed_slice)
print("Mixed Slice Shape:", mixed_slice.shape)



\nMixed Slice:
tensor([[[ 2,  3],
         [ 5,  6]],

        [[11, 12],
         [14, 15]]])
Mixed Slice Shape: torch.Size([2, 2, 2])


Slide 23 : Tensor Broadcasting Examples

In [57]:
tensor1 = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor2 = torch.tensor ([10,20,30])
result = tensor1 + tensor2
print("Broadcast addition: In", result)

Broadcast addition: In tensor([[11, 22, 33],
        [14, 25, 36]])


Slide 24: Tensor Broadcasting Examples

In [58]:
tensor1 = torch.tensor ([[1, 2,3], [4,5,6]])
tensor2 = torch.tensor([[10], [20]]) # shape: (2,1)
result = tensor1 * tensor2
print ("Broadcast Multiplication: \\n", result)



Broadcast Multiplication: \n tensor([[ 10,  20,  30],
        [ 80, 100, 120]])


Slide 27 : Tensor Reduction Examples

In [59]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]],dtype=torch.float64)
# Tensor Reduction Operations
sum_result = torch.sum(tensor)
mean_result = torch.mean(tensor)
max_result = torch.max(tensor)
min_result = torch.min(tensor)
argmax_result = torch.argmax(tensor)
argmin_result = torch.argmin(tensor)

print(sum_result)
print(mean_result)
print(max_result)
print(min_result)
print(argmax_result)
print(argmin_result)


tensor(45., dtype=torch.float64)
tensor(5., dtype=torch.float64)
tensor(9., dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(8)
tensor(0)


Slide 35: Examples of view and reshape

In [60]:
# Create a contiguous 2D tensor
tensor = torch. tensor([
	[1, 2, 3],
	[4, 5, 6]
])
# Reshape the tensor using view
reshaped_tensor = tensor.view(3, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Slide 36: Examples of view and reshape

In [61]:
import torch
# Create a non-contiguous 2D tensor using slicing
tensor = torch. tensor([[1, 2, 3, 4, 5, 6]])
sliced_tensor = tensor[:, :3]
# Reshape the tensor using reshape
reshaped_tensor = torch.reshape(sliced_tensor, (1, 3))
print ("Original Tensor:")
print (sliced_tensor)
print("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3]])
\nReshaped Tensor:
tensor([[1, 2, 3]])


Slide 37 : The -1 trick in view()

In [62]:
import torch
# Create a tensor with size (2, 4)
tensor = torch. tensor([
	[1, 2, 3, 4],
	[5, 6, 7, 8]
])
# Reshape the tensor using view and -1 trick
reshaped_tensor = tensor.view(-1, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)


Original Tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [63]:
a= torch.ones(2,3,4)
b= a.view(1,4,-1)
print(b.shape)

torch.Size([1, 4, 6])


Slide 41 : Transpose

In [64]:
import torch
# Example tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print ("Original tensor:")
print (x)
print("Shape of original tensor:", x.shape)
# Transpose the tensor
y = torch.transpose (x, 0, 1)
print ("Transposed tensor:")
print (y)
print("Shape of transposed tensor:", y.shape)



Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of original tensor: torch.Size([2, 3])
Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape of transposed tensor: torch.Size([3, 2])


Slide 42 : Concatenating tensors

In [65]:
import torch
# Create tensors
tensor1 = torch.tensor ([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
tensor2 = torch.tensor([
[10, 11, 12],
[13, 14, 15],
[16, 17, 18]
])
# Concatenate tensors along dimension 1
concatenated_tensor = torch.cat((tensor1, tensor2), dim=1)
# Display results
print ("Tensor 1:")
print (tensor1)
print ("\\nTensor 2:")
print (tensor2)
print ("\\nConcatenated Tensor:")
print (concatenated_tensor)



Tensor 1:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
\nTensor 2:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
\nConcatenated Tensor:
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])


Slide 43: Splitting Tensors

In [66]:
import torch
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]
])
# Split the tensor along dimension 0 into two parts
split_tensors = torch.split(tensor, split_size_or_sections=2, dim=0)
# Display results
print("Original Tensor:")
print (tensor)
print ("\\nSplit Tensors:")
for split_tensor in split_tensors:
  print (split_tensors)



Original Tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
\nSplit Tensors:
(tensor([[1, 2, 3],
        [4, 5, 6]]), tensor([[ 7,  8,  9],
        [10, 11, 12]]))
(tensor([[1, 2, 3],
        [4, 5, 6]]), tensor([[ 7,  8,  9],
        [10, 11, 12]]))


Slide 45: Stacking tensors

In [67]:
import torch
# Create tensors
tensor1 = torch. tensor ([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
tensor2 = torch.tensor([
[10, 11, 12],
[13, 14, 15],
[16, 17, 18]
])
# Stack tensors along a new dimension
stacked_tensor = torch.stack((tensor1, tensor2), dim=-1)
# Display results
print ("Tensor 1:")
print (tensor1)
print("\\nTensor 2:")
print (tensor2)
print ("\\nStacked Tensor:")
print (stacked_tensor)



Tensor 1:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
\nTensor 2:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
\nStacked Tensor:
tensor([[[ 1, 10],
         [ 2, 11],
         [ 3, 12]],

        [[ 4, 13],
         [ 5, 14],
         [ 6, 15]],

        [[ 7, 16],
         [ 8, 17],
         [ 9, 18]]])


In [68]:
stacked_tensor.shape

torch.Size([3, 3, 2])

Slide 51 : Example of Gradient calculation

In [69]:
import torch
# Enable gradient tracking
x = torch.tensor(3.0, requires_grad=True)
# Perform operations on the tensor
y = 2 * x + 1
z = y ** 2
# Compute gradients
z.backward()
# Access the computed gradients
x_grad = x.grad

print(x_grad)

tensor(28.)


Slide 52 : Detaching and no grad()

In [70]:
import torch
# Create a tensor with tracking enabled
x = torch.tensor([3.0], requires_grad=True)
# Perform operations on the tensor
y = x**2 + 2*x + 1
# Stop tracking gradients using detach()
z = y.detach()
# Perform further operations without tracking
with torch.no_grad() :
  w = z * 2
print(w)



tensor([32.])


Slide 53 : Advanced Autograd operations

In [71]:
import torch
x = torch. tensor([2.0], requires_grad=True)
y = torch.tensor([3.0], requires_grad=True)
z = x ** 2 + y ** 3
z.backward(retain_graph=True) # Specify retain_graph=True
print(x.grad) # Partial derivative of z with respect to x
print(y.grad) # Partial derivative of z with respect to y
z.backward (retain_graph=True)
print(x.grad) # Second-order partial derivative of z with respect to X
print(y.grad) # Second-order partial derivative of z with respect to y
z.backward ()
print(x.grad)
print(y.grad)

tensor([4.])
tensor([27.])
tensor([8.])
tensor([54.])
tensor([12.])
tensor([81.])


Slide 55: Advanced autograd operations

In [72]:
import torch
from torch.autograd.functional import hessian

# Create a tensor with requires_grad=True
x = torch.tensor([[1.0, 2.0, 3.0], [2.5, 3.5, 4.5]], requires_grad=True)

# Define a function that returns a scalar
def scalar_function(x):
  return (x ** 3).sum()

# Compute the Hessian matrix
hessian_matrix = hessian (scalar_function, x)

# Access the Hessian matrix
print (hessian_matrix)



tensor([[[[ 6.,  0.,  0.],
          [ 0.,  0.,  0.]],

         [[ 0., 12.,  0.],
          [ 0.,  0.,  0.]],

         [[ 0.,  0., 18.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [15.,  0.,  0.]],

         [[ 0.,  0.,  0.],
          [ 0., 21.,  0.]],

         [[ 0.,  0.,  0.],
          [ 0.,  0., 27.]]]])


 Slide 57: Example of Pytorch Eager mode

In [73]:
import torch
# Initializing input tensors
a = torch.tensor(15.0,requires_grad=True)
b = torch.tensor(20.0,requires_grad=True)
# Enable eager mode execution
torch.set_grad_enabled(True)
# Computing the output
c = a * b
# Computing the gradients
c.backward()
# Collecting the output gradient of the
# output with respect to the input 'a'
derivative_out_a = a.grad
# Collecting the output gradient of the
# output with respect to the input 'b'
derivative_out_b = b.grad
# Displaying the outputs
print(f'a = {a}')
print(f'b = {b}')
print (f'c = {c}')
print(f'Derivative of c with respect to a = {derivative_out_a}')
print(f'Derivative of c with respect to b = {derivative_out_b}')



a = 15.0
b = 20.0
c = 300.0
Derivative of c with respect to a = 20.0
Derivative of c with respect to b = 15.0


Slide 60: Example of JIT

In [74]:
import torch
import torch.nn as nn
# Define the model as a class
class MultiplyModel (nn.Module):
       def __init__(self):
          super(MultiplyModel, self).__init__()
          self.linear = nn.Linear(1, 1)
       def forward(self, x):
          return self.linear(x)

# Create an instance of the model
model = MultiplyModel()
# Create example inputs

a = torch.tensor([15.0])
b = torch.tensor([20.0])

# Compile the model to a static graph using JIT
model = torch.jit.trace(model, a)

# Execute the model on the inputs
c = model(a * b)

# Display the output
print (f'c = {c}')

# for p in model.parameters():
#     if p.requires_grad:
#          print(p.name, p.data)



c = tensor([90.4127], grad_fn=<ViewBackward0>)
