In [2]:
import torch
import numpy as np

### Tensor

In [3]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

- Scalar is a single number.
- Vector is an array of numbers.
- Matrix is a 2-D array of numbers.
- Tensors are N-D arrays of numbers.

In [4]:
np.array([0.0, 0.1, 0.3])
torch.tensor([0.0, 0.1, 0.2])

tensor([0.0000, 0.1000, 0.2000])

In [5]:
x = np.array([0.0, 0.1, 0.3])
torch.from_numpy(x)

tensor([0.0000, 0.1000, 0.3000], dtype=torch.float64)

In [6]:
np.ones(3)
torch.ones(3)

tensor([1., 1., 1.])

In [7]:
np.zeros(5)
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.eye(3)
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
np.arange(1,5,2)
torch.arange(1,5,2)

tensor([1, 3])

In [11]:
np.linspace(1,5,2)
torch.linspace(1,5,2)

tensor([1., 5.])

In [12]:
d = torch.zeros(2,3)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [13]:
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


In [14]:
np.random.rand(3,2)
torch.rand(2, 3)

tensor([[0.6533, 0.8508, 0.8158],
        [0.2356, 0.6515, 0.5644]])

In [15]:
d = torch.Tensor(2, 2).uniform_(-1, 1)
print(d)
print(d.type())

tensor([[ 0.9492,  0.2223],
        [-0.4159,  0.6741]])
torch.FloatTensor


In [16]:
# standard normal
np.random.randn(2, 4)
torch.randn(2,4)

tensor([[ 0.2344, -2.1505,  0.6410,  0.8682],
        [ 0.8982, -0.3118, -1.7486,  0.0984]])

In [17]:
np.random.normal(0, 0.1, 10)
torch.normal(0, 0.1, size=(1, 10))

tensor([[-0.1404,  0.0684,  0.0733,  0.0897, -0.1214,  0.0048,  0.1098, -0.0046,
          0.0384,  0.0285]])

In [18]:
np.random.uniform(0, 1, 10)
torch.distributions.Uniform(low=0, high=1)

Uniform(low: 0.0, high: 1.0)

In [19]:
np.random.permutation(10)
torch.randperm(10)

tensor([9, 8, 1, 4, 6, 3, 2, 0, 5, 7])

In [20]:
torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

tensor([1., 2., 3.])

In [21]:
indices = torch.tensor([[0,1,1], [2,0,2]])
values = torch.tensor([2,3,4], dtype=torch.float32)
x = torch.sparse_coo_tensor(indices,values, [2, 4])
print(x)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([2., 3., 4.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)


In [22]:
a = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [23]:
b = torch.tensor([1,2,3], dtype=torch.float32, device=torch.device('cpu'))

In [24]:
c = a + b
print(c)

tensor([2., 4., 6.])


In [25]:
c = torch.sub(a, b)
print(c)

tensor([0., 0., 0.])


In [26]:
a.sub(b)
print(a)

tensor([1., 2., 3.])


In [27]:
a.sub_(b)
print(a)

tensor([0., 0., 0.])


In [28]:
d = b * c
print(d)

tensor([0., 0., 0.])


In [29]:
d = torch.mul(b, c)
print(d)

tensor([0., 0., 0.])


In [30]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
a.mul(b)

tensor([1, 4, 9])

In [31]:
a.mul_(b)

tensor([1, 4, 9])

In [32]:
print(a)

tensor([1, 4, 9])


In [33]:
c = a / b
print(c)

tensor([1., 2., 3.])


In [34]:
c = torch.div(a, b)
print(c)

tensor([1., 2., 3.])


In [35]:
a.div(b)

tensor([1., 2., 3.])

In [36]:
b

tensor([1, 2, 3])

In [37]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
b = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
a.div_(b)

tensor([1., 1., 1.])

Matrix computation

In [38]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [39]:
print(torch.mm(a, b))
print(torch.matmul(a, b))
print(a @ b)
print(a.mm(b))
print(a.matmul(b))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


对于高维的tensor， 矩阵乘法作用于最后两个维度

In [40]:
a = torch.ones(1,2,3,4)
print(a)
b = torch.ones(1,2,4,3)
print(b)
print(a.matmul(b))
print(torch.matmul(a, b))

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])


In [41]:
a = torch.tensor([1,2,3], dtype=torch.float, device=torch.device('cpu'))
print(a)
print(torch.pow(a, 2))
print(a.pow(2))
print(a**2)
print(a.pow_(2))
print(a)

tensor([1., 2., 3.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1., 4., 9.])


In [42]:
print(torch.exp(a))
b = a.exp_()
print(b)

tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])


In [43]:
print(a)
print(torch.sqrt(a))
print(a.sqrt())
print(a.sqrt_())
print(a)

tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([ 1.6487,  7.3891, 90.0171])
tensor([ 1.6487,  7.3891, 90.0171])
tensor([ 1.6487,  7.3891, 90.0171])
tensor([ 1.6487,  7.3891, 90.0171])


In [44]:
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))
print(torch.log_(a))
print(a)

tensor([0.7213, 2.8854, 6.4921])
tensor([0.2171, 0.8686, 1.9543])
tensor([0.5000, 2.0000, 4.5000])
tensor([0.5000, 2.0000, 4.5000])
tensor([0.5000, 2.0000, 4.5000])


In [45]:
a = torch.rand(2, 3)
b = torch.rand(3)

In [46]:
print(a)

tensor([[0.6626, 0.1885, 0.6305],
        [0.6388, 0.5323, 0.9098]])


In [47]:
print(a.shape)

torch.Size([2, 3])


In [48]:
print(b)

tensor([0.0815, 0.1041, 0.6458])


In [49]:
print(b.shape)

torch.Size([3])


In [50]:
c = a + b

In [51]:
print(c)

tensor([[0.7440, 0.2926, 1.2764],
        [0.7202, 0.6364, 1.5556]])


In [52]:
a = torch.rand(2, 1)
b = torch.rand(2)

In [53]:
print(a)

tensor([[0.8312],
        [0.6565]])


In [54]:
print(b)

tensor([0.1544, 0.4193])


In [55]:
a + b

tensor([[0.9856, 1.2505],
        [0.8108, 1.0758]])

In [56]:
a = torch.ones(2, 1, 1, 3)
b = torch.ones(4, 2, 3)

In [57]:
print(a)

tensor([[[[1., 1., 1.]]],


        [[[1., 1., 1.]]]])


In [58]:
print(b)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [59]:
c = a + b
print(c)

tensor([[[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]]])


In [60]:
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([2, 1, 1, 3])
torch.Size([4, 2, 3])
torch.Size([2, 4, 2, 3])


In [61]:
import torch

In [62]:
a = torch.rand(2, 2)
a = a * 10
print(a)

tensor([[7.6222, 5.6206],
        [4.5963, 9.2572]])


In [63]:
print(torch.floor(a))

tensor([[7., 5.],
        [4., 9.]])


In [64]:
print(torch.ceil(a))

tensor([[ 8.,  6.],
        [ 5., 10.]])


In [65]:
print(torch.round(a))

tensor([[8., 6.],
        [5., 9.]])


In [66]:
print(torch.trunc(a))

tensor([[7., 5.],
        [4., 9.]])


In [67]:
print(torch.frac(a))

tensor([[0.6222, 0.6206],
        [0.5963, 0.2572]])


In [68]:
print(a % 2)

tensor([[1.6222, 1.6206],
        [0.5963, 1.2572]])


In [69]:
b = torch.tensor([[2, 3], [4, 5]],
                 dtype=torch.float)
print(torch.fmod(a, b))

tensor([[1.6222, 2.6206],
        [0.5963, 4.2572]])


In [70]:
print(torch.remainder(a, b))

tensor([[1.6222, 2.6206],
        [0.5963, 4.2572]])


In [71]:
a = torch.tensor([9, 9, 3])

In [72]:
print(a % 2)

tensor([1, 1, 1])


In [73]:
a = torch.tensor([-1, -9, -3])

In [74]:
print(a % 24)

tensor([23, 15, 21])


In [75]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.1965, 0.5838, 0.5431],
        [0.5268, 0.1437, 0.8363]])
tensor([[0.7771, 0.2863, 0.6690],
        [0.0982, 0.4321, 0.5763]])


In [76]:
print(torch.eq(a, b))

tensor([[False, False, False],
        [False, False, False]])


In [77]:
print(torch.equal(a, b))

False


In [78]:
print(torch.ge(a, b))

tensor([[False,  True, False],
        [ True, False,  True]])


In [79]:
print(torch.gt(a, b))

tensor([[False,  True, False],
        [ True, False,  True]])


In [80]:
print(torch.le(a, b))

tensor([[ True, False,  True],
        [False,  True, False]])


In [81]:
print(torch.lt(a, b))

tensor([[ True, False,  True],
        [False,  True, False]])


In [82]:
print(torch.ne(a, b))

tensor([[True, True, True],
        [True, True, True]])


In [83]:
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
print(a.shape)

torch.Size([2, 5])


In [84]:
print(torch.sort(a, dim=1,descending=False))

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))


In [85]:
##topk
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])


In [86]:
print(a)

tensor([[2, 4, 3, 1, 5],
        [2, 3, 5, 1, 4]])


In [87]:
print(a.shape)

torch.Size([2, 5])


In [88]:
print(torch.topk(a, k=1, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4]]),
indices=tensor([[0, 1, 0, 0, 1]]))


In [89]:
print(torch.topk(a, k=2, dim=0, largest=False))

torch.return_types.topk(
values=tensor([[2, 3, 3, 1, 4],
        [2, 4, 5, 1, 5]]),
indices=tensor([[0, 1, 0, 0, 1],
        [1, 0, 1, 1, 0]]))


In [90]:
print(torch.topk(a, k=1, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1],
        [1]]),
indices=tensor([[3],
        [3]]))


In [91]:
print(torch.topk(a, k=2, dim=1, largest=False))

torch.return_types.topk(
values=tensor([[1, 2],
        [1, 2]]),
indices=tensor([[3, 0],
        [3, 0]]))


In [92]:
print(torch.kthvalue(a, k=1, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 3, 3, 1, 4]),
indices=tensor([0, 1, 0, 0, 1]))


In [93]:
print(torch.kthvalue(a, k=2, dim=0))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))


In [94]:
print(torch.kthvalue(a, k=1, dim=1))

torch.return_types.kthvalue(
values=tensor([1, 1]),
indices=tensor([3, 3]))


In [95]:
print(torch.kthvalue(a, k=2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


In [96]:
a = torch.rand(2, 3)
print(a)
print(torch.isfinite(a))

tensor([[0.5652, 0.0250, 0.4019],
        [0.8232, 0.9642, 0.6975]])
tensor([[True, True, True],
        [True, True, True]])


In [97]:
print(a/0)
print(torch.isfinite(a/0))

tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[False, False, False],
        [False, False, False]])


In [98]:
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [99]:
import numpy as np
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([False, False,  True])


In [100]:
a = torch.rand(2, 3)
print(a)
print(torch.topk(a, k=2, dim=1, largest=False))
print(torch.topk(a, k=2, dim=1, largest=True))

tensor([[0.9347, 0.1451, 0.2881],
        [0.4806, 0.4801, 0.3483]])
torch.return_types.topk(
values=tensor([[0.1451, 0.2881],
        [0.3483, 0.4801]]),
indices=tensor([[1, 2],
        [2, 1]]))
torch.return_types.topk(
values=tensor([[0.9347, 0.2881],
        [0.4806, 0.4801]]),
indices=tensor([[0, 2],
        [0, 1]]))


In [101]:
import torch

In [102]:
a = torch.zeros(2, 3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [103]:
# torch.cos()
# torch.cosh()
# torch.sin()
# torch.sinh()
# torch.tan()
# torch.tanh()
# torch.asin()
# torch.acos()
# torch.atan()
# torch.atan2()

In [104]:
# torch.abs()
# torch.erf()
# torch.erfinv()
# torch.sigmoid()
# torch.neg()
# torch.reciprocal()
# torch.rsqrt()
# torch.sign()
# torch.lerp()
# torch.addcdiv()
# torch.addcmul()
# torch.cumprod()
# torch.cumsum()

In [105]:
a = torch.rand(2, 2)
print(torch.mean(a))
print(torch.mode(a))
print(torch.std(a))
print(torch.var(a))

tensor(0.6094)
torch.return_types.mode(
values=tensor([0.3562, 0.5949]),
indices=tensor([0, 1]))
tensor(0.1834)
tensor(0.0336)


In [106]:
# a = torch.rand(2, 2)
a = torch.ones(3, 5) * 3
print(a)
print(torch.mean(a, dim=0))
print(torch.sum(a, dim=0))
print(torch.prod(a, dim=0))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([3., 3., 3., 3., 3.])
tensor([9., 9., 9., 9., 9.])
tensor([27., 27., 27., 27., 27.])


In [107]:
print(torch.argmax(a, dim=0))
print(torch.argmin(a, dim=0))

tensor([0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0])


In [108]:
print(torch.median(a))
print(torch.mode(a))

tensor(3.)
torch.return_types.mode(
values=tensor([3., 3., 3.]),
indices=tensor([4, 4, 4]))


In [109]:
a = torch.rand(2, 2) * 10
print(a)
print(torch.histc(a, 6, 0, 0))

tensor([[3.1381, 6.7532],
        [1.4616, 2.4700]])
tensor([1., 2., 0., 0., 0., 1.])


In [110]:
a = torch.randint(0, 10, [10])
print(a)

tensor([0, 4, 8, 2, 7, 3, 5, 3, 3, 3])


In [111]:
print(torch.bincount(a))

tensor([1, 0, 1, 4, 1, 1, 0, 1, 1])


In [112]:
import torch

In [113]:
torch.manual_seed(8)

In [114]:
mean = torch.rand(1, 2)
std = torch.rand(1, 2 )
print(torch.normal(mean, std))

tensor([[1.0737, 0.9693]])


In [115]:
import torch

a = torch.rand(2, 1)
b = torch.rand(2, 1)
print(a)
print(b)

tensor([[0.5785],
        [0.1218]])
tensor([[0.9181],
        [0.6805]])


In [116]:
print(torch.dist(a, b, p = 1))
print(torch.dist(a, b, p = 2))
print(torch.dist(a, b, p = 3))

tensor(0.8984)
tensor(0.6539)
tensor(0.5978)


In [117]:
print(torch.norm(a))
print(torch.norm(a, p=2))
print(torch.norm(a, p=3))
print(torch.norm(a, p='fro'))

tensor(0.5911)
tensor(0.5911)
tensor(0.5802)
tensor(0.5911)


In [118]:
import torch

In [119]:
a = torch.rand(2, 2) * 10
print(a)

tensor([[2.0002, 1.1211],
        [0.0195, 8.9283]])


In [120]:
a = a.clamp(2, 5)
print(a)

tensor([[2.0002, 2.0000],
        [2.0000, 5.0000]])


In [121]:
# torch.where()
# torch.gather()
# torch.index_selet()
# torch.masked_select()
# torch.take()
# torch.nonzero()

In [122]:
import torch

#torch.where
a = torch.rand(4, 4)
print(a)
b = torch.rand(4, 4)
print(b)

out = torch.where(a > 0.5, a, b)
print(out)
# out = a if a > 0.5 else b

tensor([[0.8047, 0.2547, 0.4683, 0.1682],
        [0.1713, 0.5103, 0.1068, 0.5911],
        [0.7893, 0.0854, 0.3679, 0.4761],
        [0.6386, 0.4480, 0.0795, 0.3199]])
tensor([[0.0032, 0.4238, 0.3069, 0.9529],
        [0.4462, 0.7756, 0.0131, 0.4101],
        [0.8469, 0.7885, 0.6149, 0.1891],
        [0.7311, 0.9582, 0.4655, 0.7719]])
tensor([[0.8047, 0.4238, 0.3069, 0.9529],
        [0.4462, 0.5103, 0.0131, 0.5911],
        [0.7893, 0.7885, 0.6149, 0.1891],
        [0.6386, 0.9582, 0.4655, 0.7719]])


In [123]:
#torch.index_select
a = torch.rand(4, 4)
print(a)
out = torch.index_select(a, dim=0, index=torch.tensor([0, 3, 2]))
print(out, out.shape)

tensor([[0.1614, 0.6985, 0.5411, 0.9334],
        [0.7705, 0.9722, 0.4131, 0.4887],
        [0.4382, 0.4342, 0.0959, 0.1571],
        [0.3554, 0.1554, 0.0313, 0.2604]])
tensor([[0.1614, 0.6985, 0.5411, 0.9334],
        [0.3554, 0.1554, 0.0313, 0.2604],
        [0.4382, 0.4342, 0.0959, 0.1571]]) torch.Size([3, 4])


In [124]:
#torch.gather
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)

out = torch.gather(a, dim=0, index=torch.tensor([[0, 1, 1, 1],
                                 [0, 1, 2, 2],
                                 [0, 1, 3, 3]]))
print(out)
print(out.shape)

#dim=0, out[i, j, k] = input[index[i, j, k], j, k]
#dim=1, out[i, j, k] = input[i, index[i, j, k], k]
#dim=2, out[i, j, k] = input[i, j, index[i, j, k]]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])
torch.Size([3, 4])


In [125]:
#torch.masked_index
a = torch.linspace(1, 16, 16).view(4, 4)
mask = torch.gt(a, 8)
print(a)
print(mask)
out = torch.masked_select(a, mask)
print(out)

out2 = torch.masked_select(a, torch.lt(a, 8))
print(out2)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])
tensor([1., 2., 3., 4., 5., 6., 7.])


In [126]:
#torch.take
a = torch.linspace(1, 16, 16).view(4, 4)
b = torch.take(a, index=torch.tensor([0, 15, 13, 10]))
print(b)

tensor([ 1., 16., 14., 11.])


In [127]:
#torch.nonzero
print("torch.take")
a = torch.tensor([[0, 1, 2, 0], [2, 3, 0, 1]])
out = torch.nonzero(a)
print(out)
#稀疏表示

torch.take
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])


In [128]:
import torch

In [129]:
a = torch.zeros((2, 4))
b = torch.ones((2, 4))

out = torch.cat((a,b),dim=0)
print(out)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [130]:
out = torch.cat((a,b),dim=1)
print(out)

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])


In [131]:
a = torch.linspace(1, 6, 6).view(2, 3)
print(a)
b = torch.linspace(7, 12, 6).view(2, 3)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [132]:
out = torch.stack((a, b), dim=0)
print(out)
print(out.shape)
print(out[:, :, 0])
print(out[:, :, 1])

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[ 1.,  4.],
        [ 7., 10.]])
tensor([[ 2.,  5.],
        [ 8., 11.]])


In [133]:
out = torch.stack((a, b), dim=1)
print(out)
print(out.shape)
print(out[:, :, 0])
print(out[:, :, 1])

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[ 1.,  7.],
        [ 4., 10.]])
tensor([[ 2.,  8.],
        [ 5., 11.]])


In [134]:
import torch

a = torch.rand((3, 4))
print(a)

tensor([[0.5255, 0.0083, 0.6250, 0.9909],
        [0.3338, 0.2127, 0.8406, 0.5262],
        [0.7138, 0.1354, 0.1573, 0.3121]])


In [135]:
out = torch.chunk(a, 2, dim=0)
print(out[0], out[0].shape)
print(out[1], out[1].shape)

tensor([[0.5255, 0.0083, 0.6250, 0.9909],
        [0.3338, 0.2127, 0.8406, 0.5262]]) torch.Size([2, 4])
tensor([[0.7138, 0.1354, 0.1573, 0.3121]]) torch.Size([1, 4])


In [136]:
a = torch.rand((10, 4))
print(a)
out = torch.split(a, 3, dim=0)
print(len(out))
for t in out:
    print(t, t.shape)

tensor([[0.0703, 0.3213, 0.3891, 0.6951],
        [0.5847, 0.0853, 0.5330, 0.3310],
        [0.6671, 0.8568, 0.1941, 0.4324],
        [0.5946, 0.8353, 0.2842, 0.9612],
        [0.0807, 0.9035, 0.4949, 0.8818],
        [0.9615, 0.2879, 0.2843, 0.7970],
        [0.1722, 0.5268, 0.5262, 0.1233],
        [0.1214, 0.8570, 0.6483, 0.5004],
        [0.2529, 0.0029, 0.6990, 0.1578],
        [0.1766, 0.4127, 0.5507, 0.4180]])
4
tensor([[0.0703, 0.3213, 0.3891, 0.6951],
        [0.5847, 0.0853, 0.5330, 0.3310],
        [0.6671, 0.8568, 0.1941, 0.4324]]) torch.Size([3, 4])
tensor([[0.5946, 0.8353, 0.2842, 0.9612],
        [0.0807, 0.9035, 0.4949, 0.8818],
        [0.9615, 0.2879, 0.2843, 0.7970]]) torch.Size([3, 4])
tensor([[0.1722, 0.5268, 0.5262, 0.1233],
        [0.1214, 0.8570, 0.6483, 0.5004],
        [0.2529, 0.0029, 0.6990, 0.1578]]) torch.Size([3, 4])
tensor([[0.1766, 0.4127, 0.5507, 0.4180]]) torch.Size([1, 4])


In [137]:
out = torch.split(a, [1, 3, 6], dim=0)
for t in out:
    print(t, t.shape)

tensor([[0.0703, 0.3213, 0.3891, 0.6951]]) torch.Size([1, 4])
tensor([[0.5847, 0.0853, 0.5330, 0.3310],
        [0.6671, 0.8568, 0.1941, 0.4324],
        [0.5946, 0.8353, 0.2842, 0.9612]]) torch.Size([3, 4])
tensor([[0.0807, 0.9035, 0.4949, 0.8818],
        [0.9615, 0.2879, 0.2843, 0.7970],
        [0.1722, 0.5268, 0.5262, 0.1233],
        [0.1214, 0.8570, 0.6483, 0.5004],
        [0.2529, 0.0029, 0.6990, 0.1578],
        [0.1766, 0.4127, 0.5507, 0.4180]]) torch.Size([6, 4])


In [138]:
import torch

a = torch.rand(2, 3)
print(a)

tensor([[0.4895, 0.9324, 0.9331],
        [0.8262, 0.5121, 0.9032]])


In [139]:
out = torch.reshape(a, (3, 2))
print(out)

tensor([[0.4895, 0.9324],
        [0.9331, 0.8262],
        [0.5121, 0.9032]])


In [140]:
print(torch.t(out))
print(torch.transpose(out, 0, 1))

tensor([[0.4895, 0.9331, 0.5121],
        [0.9324, 0.8262, 0.9032]])
tensor([[0.4895, 0.9331, 0.5121],
        [0.9324, 0.8262, 0.9032]])


In [141]:
a = torch.rand(1, 2, 3)
out = torch.transpose(a, 0, 1)
print(out)
print(out.shape)

tensor([[[0.4676, 0.8897, 0.7086]],

        [[0.3167, 0.5485, 0.7148]]])
torch.Size([2, 1, 3])


In [142]:
out = torch.squeeze(a)
print(out)
print(out.shape)

tensor([[0.4676, 0.8897, 0.7086],
        [0.3167, 0.5485, 0.7148]])
torch.Size([2, 3])


In [143]:
print(a)

tensor([[[0.4676, 0.8897, 0.7086],
         [0.3167, 0.5485, 0.7148]]])


In [144]:
out = torch.unsqueeze(a, -1)
print(out)
print(out.shape)

tensor([[[[0.4676],
          [0.8897],
          [0.7086]],

         [[0.3167],
          [0.5485],
          [0.7148]]]])
torch.Size([1, 2, 3, 1])


In [145]:
out = torch.unbind(a, dim=2)
print(out)

(tensor([[0.4676, 0.3167]]), tensor([[0.8897, 0.5485]]), tensor([[0.7086, 0.7148]]))


In [146]:
print(a)
print(torch.flip(a, dims=[2, 1]))

tensor([[[0.4676, 0.8897, 0.7086],
         [0.3167, 0.5485, 0.7148]]])
tensor([[[0.7148, 0.5485, 0.3167],
         [0.7086, 0.8897, 0.4676]]])


In [147]:
print(a)
out = torch.rot90(a, -1, dims=[0, 2])
print(out)
print(out.shape)

tensor([[[0.4676, 0.8897, 0.7086],
         [0.3167, 0.5485, 0.7148]]])
tensor([[[0.4676],
         [0.3167]],

        [[0.8897],
         [0.5485]],

        [[0.7086],
         [0.7148]]])
torch.Size([3, 2, 1])


In [148]:
import torch

a = torch.full((2,3), 10)
print(a)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [149]:
import torch
import numpy as np

In [150]:
import cv2
data = cv2.imread("/Users/linghuang/Git/Deep-Learning/Pytorch/03/test.png")
print(data)

ModuleNotFoundError: No module named 'cv2'

In [151]:
# cv2.imshow("test1", data)
# cv2.waitKey(0)

In [152]:
# a = np.zeros([2, 2])
# out = torch.from_numpy(a)

out = torch.from_numpy(data)
out = torch.flip(out, dims=[0])
data = out.numpy()
print(data)

# out = out.to(torch.device("cuda"))
# print(out.is_cuda)

NameError: name 'data' is not defined

In [153]:
out = torch.flip(out, dims=[0])

out = out.to(torch.device("cpu"))
# out = out.to(torch.device("cuda"))

print(out.is_cuda)

data = out.numpy()

# cv2.imshow("test2", data)

# cv2.waitKey(0)

False


### Variable (autograd)

In [154]:
import torch
from torch.autograd import Variable

In [155]:
# part 1
#x = Variable(torch.ones(2, 2),
# requires_grad=True)

x = torch.ones(2, 2, requires_grad=True)
# x.register_hook(lambda grad:grad*2)

In [156]:
y = x + 2
z = y * y * 3

In [157]:
z.backward(torch.ones(2,2))
print(x.grad)

tensor([[18., 18.],
        [18., 18.]])


In [158]:
print(x.grad_fn)

None


In [159]:
print(y.grad_fn)

In [160]:
print(z.grad_fn)

In [161]:
x = torch.ones(2, 2, requires_grad=True)
x.register_hook(lambda grad:grad*2)

In [162]:
y = x + 2
z = y * y * 3
z.backward(torch.ones(2,2))
print(x.grad)

tensor([[36., 36.],
        [36., 36.]])


In [163]:
y = x + 2
z = y * y * 3
z.backward(gradient=torch.ones(2,2), retain_graph=True)
print(x.grad)

tensor([[72., 72.],
        [72., 72.]])


In [164]:
# z = torch.sum(z)
# nn = torch.rand(2, 2)
nn = torch.ones(2, 2)
print(nn)

z.backward(gradient=nn, retain_graph=True)

tensor([[1., 1.],
        [1., 1.]])


In [165]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
# z = torch.sum(z)
nn = torch.rand(2, 2)
print(nn)

z.backward(gradient=nn, retain_graph=True)

tensor([[0.2713, 0.4320],
        [0.3815, 0.6342]])


In [166]:
print(torch.autograd.backward(z, grad_tensors=nn, retain_graph=True))

None


In [167]:
print(torch.autograd.grad(z, [x], grad_outputs=nn, retain_graph=True))

(tensor([[ 4.8835,  7.7753],
        [ 6.8666, 11.4161]]),)


In [168]:
print(torch.autograd.grad(z, [x, y, z], grad_outputs=nn))

(tensor([[ 4.8835,  7.7753],
        [ 6.8666, 11.4161]]), tensor([[ 4.8835,  7.7753],
        [ 6.8666, 11.4161]]), tensor([[0.2713, 0.4320],
        [0.3815, 0.6342]]))


In [169]:
print(x.grad)
print(y.grad)
print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)

tensor([[ 9.7670, 15.5506],
        [13.7333, 22.8323]])
None
None


/var/folders/7x/tfwsytqd3yjccjl53cm75j700000gn/T/ipykernel_33128/3881871529.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(y.grad)


In [170]:
import torch

In [171]:
class line(torch.autograd.Function):
    @staticmethod
    def forward(ctx, w, x, b):
        #y = w*x +b
        ctx.save_for_backward(w, x, b)
        return w * x + b

    @staticmethod
    def backward(ctx, grad_out):
        w, x, b = ctx.saved_tensors
        grad_w = grad_out * x
        grad_x = grad_out * w
        grad_b = grad_out
        return grad_w, grad_x, grad_b

In [172]:
w = torch.rand(2, 2, requires_grad=True)
x = torch.rand(2, 2, requires_grad=True)
b = torch.rand(2, 2, requires_grad=True)

out = line.apply(w, x, b)
out.backward(torch.ones(2, 2))

print(w, x, b)
print(w.grad, x.grad, b.grad)

tensor([[0.3130, 0.4206],
        [0.4624, 0.5076]], requires_grad=True) tensor([[0.5862, 0.3389],
        [0.6046, 0.0160]], requires_grad=True) tensor([[0.3661, 0.8887],
        [0.5567, 0.4753]], requires_grad=True)
tensor([[0.5862, 0.3389],
        [0.6046, 0.0160]]) tensor([[0.3130, 0.4206],
        [0.4624, 0.5076]]) tensor([[1., 1.],
        [1., 1.]])


In [173]:
import torch

class line(torch.autograd.Function):
    @staticmethod
    def forward(ctx, w, x, b):
        #y = w*x +b
        ctx.save_for_backward(w, x, b)
        return w * x + b

    @staticmethod
    def backward(ctx, grad_out):
        w, x, b = ctx.saved_tensors

        grad_w = grad_out * x
        grad_x = grad_out * w
        grad_b = grad_out

        return grad_w, grad_x, grad_b


w = torch.rand(2, 2, requires_grad=True)
x = torch.rand(2, 2, requires_grad=True)
b = torch.rand(2, 2, requires_grad=True)

out = line.apply(w, x, b)
out.backward(torch.ones(2, 2))

print(w, x, b)
print(w.grad, x.grad, b.grad)



tensor([[0.4373, 0.1633],
        [0.5252, 0.8667]], requires_grad=True) tensor([[0.6323, 0.0848],
        [0.3054, 0.3568]], requires_grad=True) tensor([[0.8680, 0.3368],
        [0.7091, 0.3454]], requires_grad=True)
tensor([[0.6323, 0.0848],
        [0.3054, 0.3568]]) tensor([[0.4373, 0.1633],
        [0.5252, 0.8667]]) tensor([[1., 1.],
        [1., 1.]])
